/**
 * The agent API surface and its authorization contract.
 *
 * This is deliberately about routes that exist today, not one placeholder endpoint per future
 * module. A feature with no agent API yet belongs to that module's ticket; an API that does exist
 * must name the entitlement it enforces here and call requireFeature for that key.
 */
export type AgentApiPolicy = {
  sourceFile: string;
  featureKey: string | null;
  allowedRoles?: readonly string[];
};

export const AGENT_API_POLICIES: AgentApiPolicy[] = [
  { sourceFile: "app/api/app/announcements/[id]/dismiss/route.ts", featureKey: null },
  { sourceFile: "app/api/app/announcements/route.ts", featureKey: null },
  { sourceFile: "app/api/app/auth/confirm-email/route.ts", featureKey: null },
  // Signed out: emails a reset link to an existing agent account. No session, no feature.
  { sourceFile: "app/api/app/auth/forgot-password/route.ts", featureKey: null },
  { sourceFile: "app/api/app/auth/login/route.ts", featureKey: null },
  { sourceFile: "app/api/app/auth/logout/route.ts", featureKey: null },
  { sourceFile: "app/api/app/auth/set-password/route.ts", featureKey: null },
  // Switching workspace is account plumbing, not a paid module: requireTenant() with no role list,
  // and the target membership is verified server-side against the session's own user id.
  { sourceFile: "app/api/app/auth/switch-workspace/route.ts", featureKey: null },
  { sourceFile: "app/api/app/auth/workspaces/route.ts", featureKey: null },
  { sourceFile: "app/api/app/checkout/coupon/route.ts", featureKey: null },
  { sourceFile: "app/api/app/checkout/start/route.ts", featureKey: null },
  { sourceFile: "app/api/app/checkout/verify/route.ts", featureKey: null },
  // No single feature: search spans several, and gates each result group on its own page's feature
  // and roles inside lib/search/service.ts.
  { sourceFile: "app/api/app/search/route.ts", featureKey: null },
  { sourceFile: "app/api/app/agency-profile/route.ts", featureKey: null, allowedRoles: ["owner"] },
  // The support email and phone partners see; agency identity, not a feature, like the profile above.
  { sourceFile: "app/api/app/partner-support-contact/route.ts", featureKey: null, allowedRoles: ["owner"] },
  { sourceFile: "app/api/app/carrier-library/route.ts", featureKey: "appointment_vault", allowedRoles: ["owner"] },
  { sourceFile: "app/api/app/carrier-library/tenant-carriers/route.ts", featureKey: "appointment_vault", allowedRoles: ["owner"] },
  { sourceFile: "app/api/app/carrier-library/commission-schedules/route.ts", featureKey: "appointment_vault", allowedRoles: ["owner"] },
  { sourceFile: "app/api/app/carrier-library/advance-rules/route.ts", featureKey: "appointment_vault", allowedRoles: ["owner"] },
  { sourceFile: "app/api/app/appointment-vault/route.ts", featureKey: "appointment_vault", allowedRoles: ["owner"] },
  { sourceFile: "app/api/app/appointment-vault/appointments/route.ts", featureKey: "appointment_vault", allowedRoles: ["owner"] },
  { sourceFile: "app/api/app/appointment-vault/licenses/route.ts", featureKey: "appointment_vault", allowedRoles: ["owner"] },
  { sourceFile: "app/api/app/appointment-vault/eo-policies/route.ts", featureKey: "appointment_vault", allowedRoles: ["owner"] },
  { sourceFile: "app/api/app/appointment-vault/ce-records/route.ts", featureKey: "appointment_vault", allowedRoles: ["owner"] },
  { sourceFile: "app/api/app/appointment-vault/carrier-training/route.ts", featureKey: "appointment_vault", allowedRoles: ["owner"] },
  { sourceFile: "app/api/app/contacts/route.ts", featureKey: "duplicate_detection", allowedRoles: ["owner", "producer", "assistant"] },
  { sourceFile: "app/api/app/contacts/export/route.ts", featureKey: "duplicate_detection", allowedRoles: ["owner", "producer", "assistant"] },
  { sourceFile: "app/api/app/contacts/field-schema/route.ts", featureKey: "duplicate_detection", allowedRoles: ["owner", "producer", "assistant"] },
  { sourceFile: "app/api/app/contacts/import/route.ts", featureKey: "duplicate_detection", allowedRoles: ["owner", "producer", "assistant"] },
  { sourceFile: "app/api/app/contacts/merge/route.ts", featureKey: "duplicate_detection", allowedRoles: ["owner", "producer", "assistant"] },
  { sourceFile: "app/api/app/contacts/merge/undo/route.ts", featureKey: "duplicate_detection", allowedRoles: ["owner", "producer", "assistant"] },
  { sourceFile: "app/api/app/contacts/reviews/route.ts", featureKey: "duplicate_detection", allowedRoles: ["owner", "producer", "assistant"] },
  { sourceFile: "app/api/app/dial/preflight/route.ts", featureKey: "outbound_dialing", allowedRoles: ["owner", "producer"] },
  { sourceFile: "app/api/app/dialer/search/route.ts", featureKey: "outbound_dialing", allowedRoles: ["owner", "producer"] },
  { sourceFile: "app/api/app/dialer/panel/route.ts", featureKey: "outbound_dialing", allowedRoles: ["owner", "producer", "setter"] },
  { sourceFile: "app/api/app/dialer/next/route.ts", featureKey: "outbound_dialing", allowedRoles: ["owner", "producer", "setter"] },
  { sourceFile: "app/api/app/dialer/pick/route.ts", featureKey: "outbound_dialing", allowedRoles: ["owner", "producer", "setter"] },
  { sourceFile: "app/api/app/dialer/queue/route.ts", featureKey: "outbound_dialing", allowedRoles: ["owner", "producer", "setter"] },
  { sourceFile: "app/api/app/appointments/route.ts", featureKey: "outbound_dialing", allowedRoles: ["owner", "producer", "setter"] },
  // The other half of LA-2.12's role-table line: a setter books into these hours and may not change
  // them, so this route admits the roles that hold `calendar.manage` and the booking route does not.
  { sourceFile: "app/api/app/availability/route.ts", featureKey: "outbound_dialing", allowedRoles: ["owner", "producer", "assistant"] },
  { sourceFile: "app/api/app/calendar-connections/route.ts", featureKey: "outbound_dialing", allowedRoles: ["owner", "producer", "assistant"] },
  { sourceFile: "app/api/app/calendar-connections/callback/route.ts", featureKey: "outbound_dialing", allowedRoles: ["owner", "producer", "assistant"] },
  { sourceFile: "app/api/app/cadence/route.ts", featureKey: "outbound_dialing", allowedRoles: ["owner", "producer", "setter", "assistant"] },
  { sourceFile: "app/api/app/suppression/route.ts", featureKey: "tcpa_checker", allowedRoles: ["owner", "producer", "assistant", "setter"] },
  { sourceFile: "app/api/app/consent/route.ts", featureKey: "consent_locker", allowedRoles: ["owner", "producer", "assistant"] },
  { sourceFile: "app/api/app/calling-windows/route.ts", featureKey: "outbound_dialing", allowedRoles: ["owner", "producer", "setter", "assistant"] },
  { sourceFile: "app/api/app/lead-post-keys/route.ts", featureKey: "lead_import", allowedRoles: ["owner"] },
  { sourceFile: "app/api/app/lead-post-keys/[id]/route.ts", featureKey: "lead_import", allowedRoles: ["owner"] },
  // Reading the diary. A setter books into it, so a setter can see it — booking into a calendar you
  // cannot see is how two setters put two people in the same hour.
  { sourceFile: "app/api/app/calendar/route.ts", featureKey: "outbound_dialing", allowedRoles: ["owner", "producer", "setter"] },
  { sourceFile: "app/api/app/leads/import/preflight/route.ts", featureKey: "lead_import", allowedRoles: ["owner", "producer", "assistant"] },
  // The inventory of imported lists. Same feature and roles as the import that fills it.
  { sourceFile: "app/api/app/lead-lists/route.ts", featureKey: "lead_import", allowedRoles: ["owner", "producer", "assistant"] },
  { sourceFile: "app/api/app/scoring/route.ts", featureKey: "outbound_dialing", allowedRoles: ["owner", "producer"] },
  { sourceFile: "app/api/app/scoring/preview/route.ts", featureKey: "outbound_dialing", allowedRoles: ["owner", "producer"] },
  { sourceFile: "app/api/app/dialer/attempt/route.ts", featureKey: "outbound_dialing", allowedRoles: ["owner", "producer", "setter"] },
  { sourceFile: "app/api/app/dialer/attempt/[id]/click/route.ts", featureKey: "outbound_dialing", allowedRoles: ["owner", "producer", "setter"] },
  { sourceFile: "app/api/app/dialer/attempt/[id]/disclosure/route.ts", featureKey: "outbound_dialing", allowedRoles: ["owner", "producer", "setter"] },
  { sourceFile: "app/api/app/dialer/attempt/[id]/disposition/route.ts", featureKey: "outbound_dialing", allowedRoles: ["owner", "producer", "setter"] },
  // Publishing is owners and producers (the route checks it after the dialer gate); a setter reads.
  { sourceFile: "app/api/app/dialer/scripts/route.ts", featureKey: "outbound_dialing", allowedRoles: ["owner", "producer"] },
  // Publishing is owners and producers (the route checks it after the dialer gate); a setter reads.
  { sourceFile: "app/api/app/dialer/rebuttals/route.ts", featureKey: "outbound_dialing", allowedRoles: ["owner", "producer"] },
  { sourceFile: "app/api/app/campaigns/route.ts", featureKey: "outbound_dialing", allowedRoles: ["owner", "producer"] },
  { sourceFile: "app/api/app/campaigns/[id]/route.ts", featureKey: "outbound_dialing", allowedRoles: ["owner", "producer"] },
  // Re-screens every lead in a campaign and bills each screening lookup: owners only.
  { sourceFile: "app/api/app/campaigns/[id]/scrub/route.ts", featureKey: "outbound_dialing", allowedRoles: ["owner"] },
  { sourceFile: "app/api/app/vendors/route.ts", featureKey: "outbound_dialing", allowedRoles: ["owner", "producer"] },
  // Reads True CPA's figures only when the tenant also has true_cpa (checked inside the route).
  { sourceFile: "app/api/app/vendors/cards/route.ts", featureKey: "outbound_dialing", allowedRoles: ["owner", "producer"] },
  { sourceFile: "app/api/app/compliance/consent/claim/route.ts", featureKey: "lead_import", allowedRoles: ["owner", "producer"] },
  { sourceFile: "app/api/app/deal-flow/route.ts", featureKey: "daily_deal_flow", allowedRoles: ["owner", "producer"] },
  { sourceFile: "app/api/app/deal-flow/[id]/route.ts", featureKey: "daily_deal_flow", allowedRoles: ["owner", "producer"] },
  { sourceFile: "app/api/app/deal-flow/funnel/route.ts", featureKey: "daily_deal_flow", allowedRoles: ["owner", "producer"] },
  { sourceFile: "app/api/app/partner-quality/route.ts", featureKey: "partner_quality", allowedRoles: ["owner", "producer", "bookkeeper"] },
  { sourceFile: "app/api/app/partner-quality/leads/route.ts", featureKey: "partner_quality", allowedRoles: ["owner", "producer", "bookkeeper"] },
  { sourceFile: "app/api/app/true-cpa/route.ts", featureKey: "true_cpa", allowedRoles: ["owner", "producer", "bookkeeper"] },
  { sourceFile: "app/api/app/true-cpa/leads/route.ts", featureKey: "true_cpa", allowedRoles: ["owner", "producer", "bookkeeper"] },
  { sourceFile: "app/api/app/true-cpa/compare/route.ts", featureKey: "true_cpa", allowedRoles: ["owner", "producer", "bookkeeper"] },
  { sourceFile: "app/api/app/vendor-returns/route.ts", featureKey: "true_cpa", allowedRoles: ["owner", "producer", "bookkeeper"] },
  { sourceFile: "app/api/app/vendor-returns/candidates/route.ts", featureKey: "true_cpa", allowedRoles: ["owner", "producer", "bookkeeper"] },
  { sourceFile: "app/api/app/vendor-returns/cost-per-policy/route.ts", featureKey: "true_cpa", allowedRoles: ["owner", "producer", "bookkeeper"] },
  { sourceFile: "app/api/app/vendor-returns/claims/route.ts", featureKey: "true_cpa", allowedRoles: ["owner", "producer", "bookkeeper"] },
  { sourceFile: "app/api/app/vendor-returns/claims/[id]/route.ts", featureKey: "true_cpa", allowedRoles: ["owner", "producer", "bookkeeper"] },
  { sourceFile: "app/api/app/vendor-returns/import-removals/route.ts", featureKey: "true_cpa", allowedRoles: ["owner", "producer", "bookkeeper"] },
  { sourceFile: "app/api/app/ledger/route.ts", featureKey: "commission_ledger", allowedRoles: ["owner", "producer", "bookkeeper"] },
  // Carrier statement import (20260924260000). The two roles that hold `statements.view`; a producer
  // sees accepted statement lines for their own policies through the ledger route above instead.
  { sourceFile: "app/api/app/statements/route.ts", featureKey: "statement_ingestion", allowedRoles: ["owner", "bookkeeper"] },
  { sourceFile: "app/api/app/statements/preview/route.ts", featureKey: "statement_ingestion", allowedRoles: ["owner", "bookkeeper"] },
  { sourceFile: "app/api/app/statements/[id]/route.ts", featureKey: "statement_ingestion", allowedRoles: ["owner", "bookkeeper"] },
  { sourceFile: "app/api/app/statements/[id]/lines/route.ts", featureKey: "statement_ingestion", allowedRoles: ["owner", "bookkeeper"] },
  { sourceFile: "app/api/app/inbound/transfer/route.ts", featureKey: "inbound_transfers", allowedRoles: ["owner", "producer"] },
  { sourceFile: "app/api/app/inbound/route.ts", featureKey: "inbound_transfers", allowedRoles: ["owner", "producer", "assistant"] },
  // Lost transfers and today by partner; the POST (recover) narrows to owner and producer in the route.
  { sourceFile: "app/api/app/inbound/today/route.ts", featureKey: "inbound_transfers", allowedRoles: ["owner", "producer", "assistant"] },
  { sourceFile: "app/api/app/inbound/screening/route.ts", featureKey: "inbound_transfers", allowedRoles: ["owner", "producer", "assistant"] },
  { sourceFile: "app/api/app/inbound/claim/route.ts", featureKey: "inbound_transfers", allowedRoles: ["owner", "producer", "assistant"] },
  { sourceFile: "app/api/app/inbound/claim-next/route.ts", featureKey: "inbound_transfers", allowedRoles: ["owner", "producer", "assistant"] },
  { sourceFile: "app/api/app/inbound/verification/route.ts", featureKey: "inbound_transfers", allowedRoles: ["owner", "producer", "assistant"] },
  { sourceFile: "app/api/app/inbound/verification/reveal/route.ts", featureKey: "inbound_transfers", allowedRoles: ["owner", "producer", "assistant"] },
  { sourceFile: "app/api/app/inbound/handoff/route.ts", featureKey: "inbound_transfers", allowedRoles: ["owner", "producer", "assistant"] },
  { sourceFile: "app/api/app/inbound/disposition/route.ts", featureKey: "inbound_transfers", allowedRoles: ["owner", "producer"] },
  { sourceFile: "app/api/app/agent-floor/route.ts", featureKey: "inbound_transfers", allowedRoles: ["owner", "producer", "assistant"] },
  { sourceFile: "app/api/app/callbacks/route.ts", featureKey: "callback_calendar", allowedRoles: ["owner", "producer", "assistant"] },
  { sourceFile: "app/api/app/partner-chat/route.ts", featureKey: "inbound_transfers", allowedRoles: ["owner", "producer"] },
  { sourceFile: "app/api/app/partner-chat/attachments/[id]/route.ts", featureKey: "inbound_transfers", allowedRoles: ["owner", "producer"] },
  { sourceFile: "app/api/app/dispositions/config/route.ts", featureKey: "book_of_business", allowedRoles: ["owner"] },
  { sourceFile: "app/api/app/leads/[id]/route.ts", featureKey: "book_of_business", allowedRoles: ["owner", "producer", "assistant"] },
  { sourceFile: "app/api/app/leads/[id]/stage-history/route.ts", featureKey: "book_of_business", allowedRoles: ["owner", "producer", "assistant"] },
  { sourceFile: "app/api/app/leads/move/route.ts", featureKey: "book_of_business", allowedRoles: ["owner", "producer", "assistant"] },
  { sourceFile: "app/api/app/leads/pipeline-context/route.ts", featureKey: "book_of_business", allowedRoles: ["owner", "producer", "assistant"] },
  { sourceFile: "app/api/app/leads/pipeline-rules/route.ts", featureKey: "book_of_business", allowedRoles: ["owner"] },
  { sourceFile: "app/api/app/leads/[id]/preflight/route.ts", featureKey: "book_of_business", allowedRoles: ["owner", "producer", "assistant"] },
  { sourceFile: "app/api/app/leads/[id]/reopen/route.ts", featureKey: "book_of_business", allowedRoles: ["owner", "producer", "assistant"] },
  { sourceFile: "app/api/app/leads/[id]/notes/route.ts", featureKey: "book_of_business", allowedRoles: ["owner", "producer", "assistant"] },
  { sourceFile: "app/api/app/leads/[id]/record/route.ts", featureKey: "book_of_business", allowedRoles: ["owner", "producer", "assistant"] },
  { sourceFile: "app/api/app/leads/[id]/signature-readiness/route.ts", featureKey: "book_of_business", allowedRoles: ["owner", "producer", "assistant"] },
  { sourceFile: "app/api/app/notes/search/route.ts", featureKey: "book_of_business", allowedRoles: ["owner", "producer", "assistant"] },
  { sourceFile: "app/api/app/leads/[id]/disposition/route.ts", featureKey: "book_of_business", allowedRoles: ["owner", "producer"] },
  { sourceFile: "app/api/app/leads/export/route.ts", featureKey: "book_of_business", allowedRoles: ["owner", "producer", "assistant", "bookkeeper"] },
  { sourceFile: "app/api/app/leads/import/route.ts", featureKey: "lead_import", allowedRoles: ["owner", "producer", "assistant"] },
  { sourceFile: "app/api/app/leads/import/mappings/route.ts", featureKey: "lead_import", allowedRoles: ["owner", "producer", "assistant"] },
  { sourceFile: "app/api/app/leads/draft/route.ts", featureKey: "book_of_business", allowedRoles: ["owner", "producer", "assistant", "bookkeeper"] },
  { sourceFile: "app/api/app/leads/route.ts", featureKey: "book_of_business", allowedRoles: ["owner", "producer", "assistant", "bookkeeper"] },
  { sourceFile: "app/api/app/queue-sla-settings/route.ts", featureKey: "book_of_business", allowedRoles: ["owner"] },
  { sourceFile: "app/api/app/scorecard/route.ts", featureKey: null, allowedRoles: ["owner", "producer", "setter"] },
  { sourceFile: "app/api/app/activity/route.ts", featureKey: "outbound_dialing", allowedRoles: ["owner", "producer", "setter"] },
  { sourceFile: "app/api/app/appointments/close-out/route.ts", featureKey: "outbound_dialing", allowedRoles: ["owner", "producer"] },
  { sourceFile: "app/api/app/nurture/route.ts", featureKey: "outbound_dialing", allowedRoles: ["owner", "producer"] },
  { sourceFile: "app/api/app/assignments/route.ts", featureKey: "outbound_dialing", allowedRoles: ["owner", "producer", "assistant", "setter"] },
  { sourceFile: "app/api/app/outbound/application/route.ts", featureKey: "outbound_dialing", allowedRoles: ["owner", "producer"] },
  { sourceFile: "app/api/app/outbound/application/reveal/route.ts", featureKey: "outbound_dialing", allowedRoles: ["owner", "producer"] },
  { sourceFile: "app/api/app/legal/accept/route.ts", featureKey: null },
  { sourceFile: "app/api/app/me/route.ts", featureKey: null },
  // Your own profile: every role reads and edits their own record, so requireTenant() with no role
  // list; the ids come only from the verified session.
  { sourceFile: "app/api/app/profile/route.ts", featureKey: null },
  // Alert preferences are a cross-cutting agent setting, not a paid module. The route still
  // resolves tenant and current membership server-side via requireTenant().
  { sourceFile: "app/api/app/notifications/route.ts", featureKey: null },
  { sourceFile: "app/api/app/partners/route.ts", featureKey: "publisher_records", allowedRoles: ["owner", "bookkeeper"] },
  { sourceFile: "app/api/app/partners/export/route.ts", featureKey: "publisher_records", allowedRoles: ["owner", "bookkeeper"] },
  { sourceFile: "app/api/app/partners/[id]/route.ts", featureKey: "publisher_records", allowedRoles: ["owner", "bookkeeper"] },
  { sourceFile: "app/api/app/partners/[id]/users/route.ts", featureKey: "publisher_records", allowedRoles: ["owner", "bookkeeper"] },
  { sourceFile: "app/api/app/partners/[id]/users/[userId]/route.ts", featureKey: "publisher_records", allowedRoles: ["owner", "bookkeeper"] },
  { sourceFile: "app/api/app/partners/[id]/users/[userId]/resend-invite/route.ts", featureKey: "publisher_records", allowedRoles: ["owner", "bookkeeper"] },
  { sourceFile: "app/api/app/partners/[id]/affiliate-links/route.ts", featureKey: "publisher_records", allowedRoles: ["owner", "bookkeeper"] },
  { sourceFile: "app/api/app/partners/[id]/affiliate-links/[linkId]/route.ts", featureKey: "publisher_records", allowedRoles: ["owner", "bookkeeper"] },
  { sourceFile: "app/api/app/partners/[id]/form-catalog/route.ts", featureKey: "publisher_records", allowedRoles: ["owner"] },
  { sourceFile: "app/api/app/partners/[id]/form-presets/route.ts", featureKey: "publisher_records", allowedRoles: ["owner"] },
  { sourceFile: "app/api/app/partners/[id]/form-profile/route.ts", featureKey: "publisher_records", allowedRoles: ["owner"] },
  { sourceFile: "app/api/app/partners/[id]/market-access/route.ts", featureKey: "publisher_records", allowedRoles: ["owner"] },
  { sourceFile: "app/api/app/products/route.ts", featureKey: "publisher_records", allowedRoles: ["owner"] },
  { sourceFile: "app/api/app/products/[code]/route.ts", featureKey: "publisher_records", allowedRoles: ["owner"] },
  { sourceFile: "app/api/app/partners/[id]/products/route.ts", featureKey: "publisher_records", allowedRoles: ["owner"] },
  { sourceFile: "app/api/app/partners/[id]/submission-setup/route.ts", featureKey: "publisher_records", allowedRoles: ["owner", "bookkeeper"] },
  { sourceFile: "app/api/app/partners/[id]/users/[userId]/admin-assignment/route.ts", featureKey: "publisher_records", allowedRoles: ["owner"] },
  { sourceFile: "app/api/app/partners/[id]/users/[userId]/form-profile/route.ts", featureKey: "publisher_records", allowedRoles: ["owner"] },
  { sourceFile: "app/api/app/partners/[id]/users/[userId]/market-access/route.ts", featureKey: "publisher_records", allowedRoles: ["owner"] },
  { sourceFile: "app/api/app/onboarding/business-profile/route.ts", featureKey: null },
  { sourceFile: "app/api/app/onboarding/status/route.ts", featureKey: null },
  { sourceFile: "app/api/app/onboarding/verification/route.ts", featureKey: null },
  { sourceFile: "app/api/app/pipelines/route.ts", featureKey: "book_of_business", allowedRoles: ["owner"] },
  { sourceFile: "app/api/app/pipelines/[id]/route.ts", featureKey: "book_of_business", allowedRoles: ["owner"] },
  { sourceFile: "app/api/app/pipelines/[id]/stages/route.ts", featureKey: "book_of_business", allowedRoles: ["owner"] },
  { sourceFile: "app/api/app/pipelines/[id]/stages/reorder/route.ts", featureKey: "book_of_business", allowedRoles: ["owner"] },
  { sourceFile: "app/api/app/pipelines/[id]/stages/[stageId]/route.ts", featureKey: "book_of_business", allowedRoles: ["owner"] },
  { sourceFile: "app/api/app/pipelines/dispositions/route.ts", featureKey: "book_of_business", allowedRoles: ["owner"] },
  // Mark issued / Mark lapsed on a deal: writes tenant_issued_policies, which the vendor scorecard
  // counts. Deal flow's feature and roles, because a deal is where the issue is learned.
  { sourceFile: "app/api/app/policies/issued/[id]/route.ts", featureKey: "daily_deal_flow", allowedRoles: ["owner", "producer"] },
  { sourceFile: "app/api/app/policies/issued/route.ts", featureKey: "daily_deal_flow", allowedRoles: ["owner", "producer"] },
  { sourceFile: "app/api/app/policies/lapse-risk/route.ts", featureKey: "chargeback_radar", allowedRoles: ["owner", "producer"] },
  // Records and resolves lapse signals. Resolving as "lapsed" also writes the policy's status, so
  // that branch additionally passes the book_of_business write gate the policies PATCH uses.
  { sourceFile: "app/api/app/policies/lapse-risk/signals/route.ts", featureKey: "chargeback_radar", allowedRoles: ["owner", "producer"] },
  { sourceFile: "app/api/app/policies/route.ts", featureKey: "book_of_business", allowedRoles: ["owner", "producer", "bookkeeper"] },
  { sourceFile: "app/api/app/signup/route.ts", featureKey: null },
  { sourceFile: "app/api/app/templates/[id]/route.ts", featureKey: "book_of_business", allowedRoles: ["owner"] },
  { sourceFile: "app/api/app/templates/assignment/route.ts", featureKey: "book_of_business", allowedRoles: ["owner"] },
  { sourceFile: "app/api/app/templates/preview/route.ts", featureKey: "book_of_business", allowedRoles: ["owner"] },
  { sourceFile: "app/api/app/templates/route.ts", featureKey: "book_of_business", allowedRoles: ["owner"] },
  { sourceFile: "app/api/app/team/[userId]/route.ts", featureKey: null, allowedRoles: ["owner"] },
  { sourceFile: "app/api/app/team/[userId]/invite/route.ts", featureKey: null, allowedRoles: ["owner"] },
  { sourceFile: "app/api/app/team/[userId]/licensed-states/route.ts", featureKey: null, allowedRoles: ["owner"] },
  { sourceFile: "app/api/app/team/[userId]/resend-invite/route.ts", featureKey: null, allowedRoles: ["owner"] },
  { sourceFile: "app/api/app/team/route.ts", featureKey: null, allowedRoles: ["owner"] },
];
