"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { ArrowLeft, CheckCircle2, Clock3, GitBranch, Hand, Loader2, MessageSquare, ShieldCheck } from "lucide-react";
import { toast } from "sonner";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Label } from "@/components/ui/label";

type Template = { product_name: string; definition_version?: number; fields: Array<{ field_key: string; label: string; type: string; is_required: boolean; options: string[]; help_text?: string | null }>; form_definition: { sections: Array<{ section_key: string; label: string; fields: Array<{ field_key: string; is_required: boolean; show_when: { field_key: string; equals: string } | null; conditional_on?: { field_key: string; equals: string } | null }> }> } };
type Event = { id: string; label: string; at: string; actor: string; detail: string | null; immutable: true };
type Workspace = { lead: { id: string; values: Record<string, unknown>; product_line: string; definition_version: number; created_at: string; updated_at: string }; template: Template; queue: { id: string; status: string; owner_user_id: string | null; claimed_at: string | null; disposition: string | null } | null; partner: { name: string; partner_type: string } | null; stage: { id: string; name: string; stage_type: string; color: string } | null; stages: Array<{ id: string; name: string; stage_type: string; color: string }>; submitter: { name: string } | null; owner: { name: string } | null; screening: { outcome: string | null; warning: string | null; checkedAt: string | null }; disposition: { label: string } | null; verification: { session: { status: string; progress_percentage: number; started_at: string; completed_at: string | null }; fields: Array<{ field_key: string; state: string; old_value: unknown; new_value: unknown; confirmed_at: string | null }> } | null; corrections: Array<{ id: string; field_key: string; old_value: unknown; new_value: unknown; actor_id: string | null; created_at: string }>; timeline: Event[]; role: string; currentUserId: string; licensedAgents: Array<{ id: string; name: string; role: string }>; pendingHandoff: { id: string; workItemId: string } | null; actions: { canClaim: boolean; canHandoff: boolean; canAcceptHandoff: boolean; canDisposition: boolean; canChangeStage: boolean }; readOnly: boolean };

function display(value: unknown) { return Array.isArray(value) ? value.join(", ") : value === null || value === undefined || value === "" ? "Not provided" : String(value); }
function when(value: string) { return new Date(value).toLocaleString([], { dateStyle: "medium", timeStyle: "short" }); }
function visible(field: { show_when: { field_key: string; equals: string } | null; conditional_on?: { field_key: string; equals: string } | null }, values: Record<string, unknown>) { const condition = field.show_when ?? field.conditional_on; if (!condition) return true; const current = values[condition.field_key]; return Array.isArray(current) ? current.includes(condition.equals) : String(current ?? "") === condition.equals; }
function stateVariant(state: string) { return state === "outstanding" ? "destructive" : state === "corrected" ? "outline" : "secondary"; }

function ApplicationTab({ data }: { data: Workspace }) {
  const corrections = useMemo(() => new Map(data.corrections.map((change) => [change.field_key, change])), [data.corrections]);
  const fields = useMemo(() => new Map(data.template.fields.map((field) => [field.field_key, field])), [data.template.fields]);
  return <div className="space-y-4"><div className="rounded-md border bg-muted/20 p-3 text-sm text-muted-foreground">Read-only snapshot of the partner-submitted application. This remains tied to form version {data.lead.definition_version}.</div>{data.template.form_definition.sections.map((section) => <Card key={section.section_key}><CardHeader className="pb-3"><CardTitle className="text-base">{section.label}</CardTitle></CardHeader><CardContent className="space-y-3">{section.fields.filter((field) => visible(field, data.lead.values)).map((formField) => { const field = fields.get(formField.field_key); if (!field) return null; const change = corrections.get(field.field_key); return <div key={field.field_key} className="grid gap-2 rounded-md border p-3 sm:grid-cols-[minmax(160px,0.7fr)_minmax(0,1.3fr)]"><div><p className="text-sm font-medium">{field.label}{(formField.is_required || field.is_required) && <span className="text-destructive"> *</span>}</p>{field.help_text && <p className="mt-1 text-xs text-muted-foreground">{field.help_text}</p>}</div><div className="min-w-0 text-sm"><p className="break-words">{display(data.lead.values[field.field_key])}</p>{change && <div className="mt-2 grid gap-2 rounded border border-amber-500/40 bg-amber-500/10 p-2 text-xs sm:grid-cols-2"><p><span className="font-semibold">Originally submitted:</span> {display(change.old_value)}</p><p><span className="font-semibold">Corrected during verification:</span> {display(change.new_value)}</p></div>}</div></div>; })}</CardContent></Card>)}</div>;
}

function VerificationTab({ data }: { data: Workspace }) {
  if (!data.verification) return <Card><CardContent className="p-6 text-sm text-muted-foreground">Verification has not started for this lead. Claim the transfer from the inbox or Floor to begin.</CardContent></Card>;
  return <div className="space-y-4"><Card><CardContent className="space-y-3 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wide text-muted-foreground">Verification progress</p><p className="mt-1 text-2xl font-extrabold">{data.verification.session.progress_percentage}%</p></div><Badge variant={data.verification.session.progress_percentage === 100 ? "secondary" : "outline"}>{data.verification.session.status}</Badge></div><div className="h-3 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary" style={{ width: `${data.verification.session.progress_percentage}%` }} /></div><p className="text-xs text-muted-foreground">Started {when(data.verification.session.started_at)}{data.verification.session.completed_at ? ` · completed ${when(data.verification.session.completed_at)}` : ""}</p></CardContent></Card><Card><CardHeader className="pb-3"><CardTitle className="text-base">Field confirmation</CardTitle></CardHeader><CardContent className="space-y-2">{data.verification.fields.map((field) => <div key={field.field_key} className="flex flex-wrap items-center justify-between gap-3 rounded-md border p-3 text-sm"><span>{field.field_key}</span><div className="flex items-center gap-2"><Badge variant={stateVariant(field.state)}>{field.state}</Badge>{field.state === "corrected" && <span className="text-xs text-muted-foreground">{display(field.old_value)} → {display(field.new_value)}</span>}</div></div>)}</CardContent></Card>{data.queue && data.queue.owner_user_id === data.currentUserId && <Button asChild><Link href={`/app/inbound/${data.queue.id}/verification`}>Open live verification</Link></Button>}</div>;
}

function NotesTab() { return <Card><CardContent className="space-y-2 p-6"><div className="flex items-center gap-2 font-semibold"><MessageSquare className="size-4" />Notes</div><p className="text-sm text-muted-foreground">Internal and shared lead notes will appear here when LA-1.21 is available. No note data is loaded or exposed until that dependency is installed.</p></CardContent></Card>; }

export function LeadDetailWorkspace({ leadId }: { leadId: string }) {
  const [data, setData] = useState<Workspace | null>(null);
  const [tab, setTab] = useState<"application" | "verification" | "notes" | "timeline">("application");
  const [error, setError] = useState("");
  const [saving, setSaving] = useState<string | null>(null);
  const [handoffTarget, setHandoffTarget] = useState("");

  const load = useCallback(async () => { const response = await fetch(`/api/app/leads/${encodeURIComponent(leadId)}`, { cache: "no-store" }); const body = await response.json().catch(() => null); if (!response.ok) { setError(body?.error ?? "Could not load this lead"); return; } setData(body); setError(""); }, [leadId]);
  // This is the server-backed detail snapshot and intentionally hydrates the client workspace.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { void load(); }, [load]);

  async function action(name: string, path: string, init: RequestInit, success: string) { setSaving(name); const response = await fetch(path, init); const body = await response.json().catch(() => null); setSaving(null); if (!response.ok) { toast.error(body?.error ?? "The action could not be completed"); return; } toast.success(success); await load(); }
  function claim() { if (!data?.queue) return; void action("claim", "/api/app/inbound/claim", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ work_item_id: data.queue.id }) }, "Transfer claimed"); }
  function moveStage(event: React.ChangeEvent<HTMLSelectElement>) { if (!data) return; void action("stage", `/api/app/leads/${data.lead.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ values: data.lead.values, stage_id: event.target.value }) }, "Stage changed"); }
  function handoff() { if (!data?.queue || !handoffTarget) { toast.error("Choose a licensed agent before offering the handoff"); return; } void action("handoff", "/api/app/inbound/handoff", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "offer", work_item_id: data.queue.id, target_user_id: handoffTarget }) }, "Handoff offered"); }
  function acceptHandoff() { if (!data?.pendingHandoff) return; void action("accept", "/api/app/inbound/handoff", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "accept", handoff_id: data.pendingHandoff.id }) }, "Handoff accepted"); }
  function nudge() { if (!data?.queue) return; void action("nudge", "/api/app/agent-floor", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "nudge", work_item_id: data.queue.id, idempotency_key: crypto.randomUUID() }) }, "Team nudged"); }

  if (error) return <Card><CardContent className="space-y-3 p-6"><p role="alert" className="text-sm text-destructive">{error}</p><Button variant="outline" onClick={() => void load()}>Try again</Button></CardContent></Card>;
  if (!data) return <div className="flex items-center gap-2 text-sm text-muted-foreground"><Loader2 className="size-4 animate-spin" />Loading lead workspace…</div>;
  const readOnly = data.readOnly;
  const tabs = [{ key: "application", label: "Application" }, { key: "verification", label: "Verification" }, { key: "notes", label: "Notes" }, { key: "timeline", label: "Timeline" }] as const;
  return <div className="mx-auto max-w-7xl space-y-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><Link href="/app/leads" className="inline-flex items-center gap-1 text-sm text-muted-foreground underline-offset-4 hover:underline focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"><ArrowLeft className="size-4" />Back to leads</Link><div className="mt-3 flex flex-wrap items-center gap-2"><h1 className="text-2xl font-extrabold tracking-tight">{display(data.lead.values.full_name ?? data.lead.values.name ?? "Unnamed lead")}</h1>{data.screening.outcome && <Badge variant={data.screening.outcome === "blocked" ? "destructive" : data.screening.warning ? "outline" : "secondary"}><ShieldCheck className="size-3" />Screening {data.screening.outcome}</Badge>}{data.queue?.status && <Badge variant="outline">{data.queue.status}</Badge>}</div><p className="mt-1 text-sm text-muted-foreground">{data.partner?.name ?? "Direct lead"} · {data.template.product_name} · submitted {when(data.lead.created_at)}</p>{data.screening.warning && <p className="mt-2 rounded-md border border-amber-500/40 bg-amber-500/10 px-3 py-2 text-sm text-amber-800">⚠ {data.screening.warning}</p>}</div><div className="flex flex-wrap items-center gap-2">{data.queue && <Button variant="outline" disabled={readOnly || saving === "nudge"} onClick={nudge}>Nudge team</Button>}{data.actions.canClaim && <Button disabled={readOnly || saving === "claim"} onClick={claim}>{saving === "claim" ? <Loader2 className="size-4 animate-spin" /> : <CheckCircle2 className="size-4" />}{readOnly ? "Read-only" : "Claim"}</Button>}{data.actions.canAcceptHandoff && <Button disabled={readOnly || saving === "accept"} onClick={acceptHandoff}>Accept handoff</Button>}{data.queue && data.actions.canHandoff && <><select aria-label="Licensed agent for handoff" disabled={readOnly || saving === "handoff"} value={handoffTarget || data.licensedAgents[0]?.id || ""} onChange={(event) => setHandoffTarget(event.target.value)} className="border-input bg-background h-9 rounded-md border px-2 text-sm"><option value="">Choose agent…</option>{data.licensedAgents.map((agent) => <option key={agent.id} value={agent.id}>{agent.name} ({agent.role})</option>)}</select><Button variant="outline" disabled={readOnly || saving === "handoff"} onClick={handoff}><Hand className="size-4" />Hand off</Button></>}{data.queue && data.actions.canDisposition && <Button asChild variant="outline"><Link href={`/app/inbound/${data.queue.id}/disposition`}>Disposition</Link></Button>}{data.queue && data.queue.owner_user_id === data.currentUserId && <Button asChild variant="outline"><Link href={`/app/inbound/${data.queue.id}/verification`}>Verification</Link></Button>}</div></div>
    <Card><CardContent className="grid gap-4 p-4 sm:grid-cols-2 lg:grid-cols-4"><div><p className="text-xs text-muted-foreground">Partner</p><p className="mt-1 font-medium">{data.partner?.name ?? "Direct"}</p></div><div><p className="text-xs text-muted-foreground">Submitted by</p><p className="mt-1 font-medium">{data.submitter?.name ?? "System"}</p></div><div><p className="text-xs text-muted-foreground">Owner</p><p className="mt-1 font-medium">{data.owner?.name ?? "Unclaimed"}</p></div><div><Label htmlFor="lead-stage">Stage</Label>{data.stage && <select id="lead-stage" disabled={readOnly || !data.actions.canChangeStage || saving === "stage"} value={data.stage.id} onChange={moveStage} className="border-input bg-background mt-1 h-9 w-full rounded-md border px-2 text-sm">{data.stages.map((stage) => <option key={stage.id} value={stage.id}>{stage.name}</option>)}</select>}</div></CardContent></Card>
    <div className="flex flex-wrap gap-2 border-b" role="tablist" aria-label="Lead detail sections">{tabs.map((item) => <button key={item.key} type="button" role="tab" aria-selected={tab === item.key} onClick={() => setTab(item.key)} className={`border-b-2 px-3 py-2 text-sm font-medium outline-none focus-visible:ring-2 focus-visible:ring-ring ${tab === item.key ? "border-primary text-primary" : "border-transparent text-muted-foreground"}`}>{item.label}</button>)}</div>
    {tab === "application" && <ApplicationTab data={data} />}{tab === "verification" && <VerificationTab data={data} />}{tab === "notes" && <NotesTab />}{tab === "timeline" && <Card><CardContent className="p-6"><div className="mb-4 flex items-center gap-2"><Clock3 className="size-4" /><p className="font-semibold">Immutable lead timeline</p></div><ol className="space-y-4 border-l pl-5">{data.timeline.map((event) => <li key={event.id} className="relative"><span className="absolute -left-[1.43rem] top-1 size-2 rounded-full bg-primary" /><p className="font-medium">{event.label}</p><p className="text-xs text-muted-foreground">{event.actor} · {when(event.at)}</p>{event.detail && <p className="mt-1 break-words text-sm text-muted-foreground">{event.detail}</p>}</li>)}</ol>{data.timeline.length === 0 && <p className="text-sm text-muted-foreground">No events recorded yet.</p>}<p className="mt-5 flex items-center gap-2 text-xs text-muted-foreground"><GitBranch className="size-3" />Events are append-only audit records.</p></CardContent></Card>}
  </div>;
}
