"use client";

import { useEffect, useMemo, useState } from "react";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import type { Pipeline, PipelineStage, PartnerPipelineType } from "@/lib/pipelines/types";

type Mapping = { id: string; stage_id: string; disposition_key: string };
const typeLabel: Record<PartnerPipelineType, string> = { publisher: "Publisher / transfer", marketing: "Marketing", affiliate: "Affiliate" };

export function PipelineSettings() {
  const [pipelines, setPipelines] = useState<Pipeline[]>([]);
  const [mappings, setMappings] = useState<Mapping[]>([]);
  const [selectedId, setSelectedId] = useState("");
  const [newName, setNewName] = useState("");
  const [newType, setNewType] = useState<PartnerPipelineType>("marketing");
  const [newStage, setNewStage] = useState({ name: "", stage_type: "open", color: "#64748b" });
  const [newDisposition, setNewDisposition] = useState({ stage_id: "", disposition_key: "" });
  const [draggedId, setDraggedId] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);

  async function load() {
    setLoading(true);
    const [pipelineResponse, mappingResponse] = await Promise.all([fetch("/api/app/pipelines", { cache: "no-store" }), fetch("/api/app/pipelines/dispositions", { cache: "no-store" })]);
    const pipelineBody = await pipelineResponse.json().catch(() => null); const mappingBody = await mappingResponse.json().catch(() => null); setLoading(false);
    if (!pipelineResponse.ok) { toast.error(pipelineBody?.error ?? "Could not load pipelines"); return; }
    setPipelines(pipelineBody.pipelines ?? []); setMappings(mappingBody?.mappings ?? []); setSelectedId((current) => current || pipelineBody.pipelines?.[0]?.id || "");
  }
  // Initial data is external server state; this effect hydrates the interactive settings panel.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { void load(); }, []);
  const selected = pipelines.find((pipeline) => pipeline.id === selectedId) ?? null;
  const allStages = useMemo(() => pipelines.flatMap((pipeline) => pipeline.stages.filter((stage) => !stage.is_archived).map((stage) => ({ ...stage, pipelineName: pipeline.name }))), [pipelines]);
  function replaceStage(stage: PipelineStage) { setPipelines((items) => items.map((pipeline) => pipeline.id === stage.pipeline_id ? { ...pipeline, stages: pipeline.stages.map((item) => item.id === stage.id ? stage : item) } : pipeline)); }
  async function request(url: string, method: string, payload: unknown) { const response = await fetch(url, { method, headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const body = await response.json().catch(() => null); if (!response.ok) throw new Error(body?.error ?? "Could not save pipeline settings"); return body; }
  async function createPipeline(event: React.FormEvent) { event.preventDefault(); try { const body = await request("/api/app/pipelines", "POST", { name: newName, partner_type: newType }); setPipelines((items) => [...items, { ...body.pipeline, stages: [] }]); setSelectedId(body.pipeline.id); setNewName(""); toast.success("Pipeline created"); } catch (error) { toast.error(error instanceof Error ? error.message : "Could not create pipeline"); } }
  async function editStage(stage: PipelineStage, patch: Partial<PipelineStage>) { try { const body = await request(`/api/app/pipelines/${stage.pipeline_id}/stages/${stage.id}`, "PATCH", patch); replaceStage(body.stage); toast.success("Stage saved"); } catch (error) { toast.error(error instanceof Error ? error.message : "Could not save stage"); } }
  async function createStage(event: React.FormEvent) { event.preventDefault(); if (!selected) return; try { const body = await request(`/api/app/pipelines/${selected.id}/stages`, "POST", newStage); setPipelines((items) => items.map((pipeline) => pipeline.id === selected.id ? { ...pipeline, stages: [...pipeline.stages, body.stage] } : pipeline)); setNewStage({ name: "", stage_type: "open", color: "#64748b" }); toast.success("Stage added"); } catch (error) { toast.error(error instanceof Error ? error.message : "Could not add stage"); } }
  async function archive(stage: PipelineStage) { if (!window.confirm(`Archive ${stage.name}? Existing leads will remain readable, but the stage will leave future pickers.`)) return; try { const body = await request(`/api/app/pipelines/${stage.pipeline_id}/stages/${stage.id}`, "PATCH", { is_archived: true }); replaceStage(body.stage); toast.success("Stage archived"); } catch (error) { toast.error(error instanceof Error ? error.message : "Could not archive stage"); } }
  async function dropStage(target: PipelineStage) { if (!selected || !draggedId || draggedId === target.id) return; const stages = [...selected.stages].filter((stage) => !stage.is_archived); const from = stages.findIndex((stage) => stage.id === draggedId); const to = stages.findIndex((stage) => stage.id === target.id); if (from < 0 || to < 0) return; const [moved] = stages.splice(from, 1); stages.splice(to, 0, moved); try { const body = await request(`/api/app/pipelines/${selected.id}/stages/reorder`, "POST", { stage_ids: stages.map((stage) => stage.id) }); setPipelines((items) => items.map((pipeline) => pipeline.id === selected.id ? { ...pipeline, stages: body.stages } : pipeline)); toast.success("Stage order saved"); } catch (error) { toast.error(error instanceof Error ? error.message : "Could not reorder stages"); } finally { setDraggedId(null); } }
  async function mapDisposition(event: React.FormEvent) { event.preventDefault(); try { const body = await request("/api/app/pipelines/dispositions", "POST", newDisposition); setMappings((items) => [...items.filter((item) => item.id !== body.mapping.id && item.stage_id !== body.mapping.stage_id && item.disposition_key !== body.mapping.disposition_key), body.mapping]); setNewDisposition({ stage_id: "", disposition_key: "" }); toast.success("Disposition mapped"); } catch (error) { toast.error(error instanceof Error ? error.message : "Could not map disposition"); } }
  async function removeMapping(id: string) { try { await request("/api/app/pipelines/dispositions", "DELETE", { id }); setMappings((items) => items.filter((item) => item.id !== id)); toast.success("Mapping removed"); } catch (error) { toast.error(error instanceof Error ? error.message : "Could not remove mapping"); } }
  if (loading) return <Card><CardContent className="p-6 text-sm text-muted-foreground">Loading pipeline settings…</CardContent></Card>;
  return <div className="space-y-6"><Card><CardHeader><CardTitle className="text-base">Pipelines</CardTitle><p className="text-sm text-muted-foreground">Each partner type has its own ordered stages. Changes apply to this tenant only.</p></CardHeader><CardContent className="space-y-4"><div className="flex flex-wrap gap-2">{pipelines.map((pipeline) => <Button key={pipeline.id} type="button" variant={pipeline.id === selectedId ? "default" : "outline"} onClick={() => setSelectedId(pipeline.id)}>{typeLabel[pipeline.partner_type]} · {pipeline.name}{pipeline.is_default && <Badge variant="secondary" className="ml-1">Default</Badge>}</Button>)}</div><form onSubmit={createPipeline} className="grid gap-3 rounded-md border bg-muted/20 p-3 sm:grid-cols-[1fr_180px_auto] sm:items-end"><div className="space-y-1"><Label htmlFor="new-pipeline-name">New pipeline name</Label><Input id="new-pipeline-name" value={newName} maxLength={120} onChange={(event) => setNewName(event.target.value)} placeholder="Qualified referrals" required /></div><div className="space-y-1"><Label htmlFor="new-pipeline-type">Partner type</Label><select id="new-pipeline-type" className="border-input bg-background h-9 w-full rounded-md border px-3 text-sm" value={newType} onChange={(event) => setNewType(event.target.value as PartnerPipelineType)}><option value="publisher">Publisher / transfer</option><option value="marketing">Marketing</option><option value="affiliate">Affiliate</option></select></div><Button type="submit">Create pipeline</Button></form></CardContent></Card>
    {selected && <Card><CardHeader><CardTitle className="text-base">{selected.name} stages</CardTitle><p className="text-sm text-muted-foreground">Drag a stage to reorder it. Existing leads keep their stage when you archive it; archived stages disappear from pickers.</p></CardHeader><CardContent className="space-y-3"><div className="space-y-2">{selected.stages.filter((stage) => !stage.is_archived).map((stage) => <div key={stage.id} draggable onDragStart={() => setDraggedId(stage.id)} onDragOver={(event) => event.preventDefault()} onDrop={() => void dropStage(stage)} className="grid gap-2 rounded-md border p-3 sm:grid-cols-[1fr_110px_100px_auto] sm:items-end"><div className="space-y-1"><Label htmlFor={`stage-name-${stage.id}`}>Stage name</Label><Input id={`stage-name-${stage.id}`} defaultValue={stage.name} maxLength={120} onBlur={(event) => { if (event.target.value !== stage.name) void editStage(stage, { name: event.target.value }); }} /></div><div className="space-y-1"><Label htmlFor={`stage-type-${stage.id}`}>Type</Label><select id={`stage-type-${stage.id}`} className="border-input bg-background h-9 w-full rounded-md border px-2 text-sm" value={stage.stage_type} onChange={(event) => void editStage(stage, { stage_type: event.target.value as PipelineStage["stage_type"] })}><option value="open">Open</option><option value="won">Won</option><option value="lost">Lost</option></select></div><div className="space-y-1"><Label htmlFor={`stage-color-${stage.id}`}>Colour</Label><Input id={`stage-color-${stage.id}`} type="text" maxLength={7} value={stage.color} onChange={(event) => replaceStage({ ...stage, color: event.target.value })} onBlur={(event) => void editStage(stage, { color: event.target.value })} /></div><Button type="button" variant="ghost" className="text-destructive" onClick={() => void archive(stage)}>Archive</Button></div>)}</div><form onSubmit={createStage} className="grid gap-3 rounded-md border bg-muted/20 p-3 sm:grid-cols-[1fr_110px_100px_auto] sm:items-end"><div className="space-y-1"><Label htmlFor="new-stage-name">New stage</Label><Input id="new-stage-name" maxLength={120} value={newStage.name} onChange={(event) => setNewStage({ ...newStage, name: event.target.value })} placeholder="Needs review" required /></div><div className="space-y-1"><Label htmlFor="new-stage-type">Type</Label><select id="new-stage-type" className="border-input bg-background h-9 w-full rounded-md border px-2 text-sm" value={newStage.stage_type} onChange={(event) => setNewStage({ ...newStage, stage_type: event.target.value })}><option value="open">Open</option><option value="won">Won</option><option value="lost">Lost</option></select></div><div className="space-y-1"><Label htmlFor="new-stage-color">Colour</Label><Input id="new-stage-color" maxLength={7} value={newStage.color} onChange={(event) => setNewStage({ ...newStage, color: event.target.value })} /></div><Button type="submit">Add stage</Button></form></CardContent></Card>}
    <Card><CardHeader><CardTitle className="text-base">Disposition mapping</CardTitle><p className="text-sm text-muted-foreground">A disposition can map to one stage per tenant. Recording that disposition moves the lead server-side.</p></CardHeader><CardContent className="space-y-4"><form onSubmit={mapDisposition} className="grid gap-3 rounded-md border bg-muted/20 p-3 sm:grid-cols-[1fr_1fr_auto] sm:items-end"><div className="space-y-1"><Label htmlFor="mapping-stage">Stage</Label><select id="mapping-stage" className="border-input bg-background h-9 w-full rounded-md border px-2 text-sm" value={newDisposition.stage_id} onChange={(event) => setNewDisposition({ ...newDisposition, stage_id: event.target.value })} required><option value="">Choose a stage</option>{allStages.map((stage) => <option key={stage.id} value={stage.id}>{stage.pipelineName} · {stage.name}</option>)}</select></div><div className="space-y-1"><Label htmlFor="mapping-key">Disposition key</Label><Input id="mapping-key" maxLength={80} pattern="[a-z][a-z0-9_]{1,79}" value={newDisposition.disposition_key} onChange={(event) => setNewDisposition({ ...newDisposition, disposition_key: event.target.value })} placeholder="needs_callback" required /></div><Button type="submit">Save mapping</Button></form><div className="space-y-2">{mappings.map((mapping) => <div key={mapping.id} className="flex flex-wrap items-center justify-between gap-2 rounded-md border p-3 text-sm"><span><code>{mapping.disposition_key}</code> → {allStages.find((stage) => stage.id === mapping.stage_id)?.name ?? "Archived stage"}</span><Button type="button" variant="ghost" className="text-destructive" onClick={() => void removeMapping(mapping.id)}>Remove</Button></div>)}</div></CardContent></Card>
  </div>;
}
