"use client";

import { useEffect, useState } from "react";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import type { TemplateField, TemplateFormDefinition, TemplateStage } from "@/lib/templates/constants";

type Current = { tenant_template_id: string; assignment: { template_id: string; template_version: number; product_code: string }; template: { name: string; description: string | null; product_name: string; version: number; fields: TemplateField[]; stages: TemplateStage[]; form_definition: TemplateFormDefinition }; latest: { id: string; version: number; name: string } | null };
type Available = { id: string; name: string; product_code: string; product_name: string; version: number; description: string | null };
type Preview = { fieldsToAdd: string[]; stagesToAdd: string[]; sectionsToAdd: string[]; alreadyApplied: boolean };

function TemplateEditor({ current, onSaved }: { current: Current; onSaved: (next: Current) => void }) {
  const [name, setName] = useState(current.template.name);
  const [fields, setFields] = useState(current.template.fields);
  const [stages, setStages] = useState(current.template.stages);
  const [saving, setSaving] = useState(false);
  async function save() {
    setSaving(true);
    const response = await fetch(`/api/app/templates/${current.tenant_template_id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name, description: current.template.description, fields, stages, form_definition: current.template.form_definition }) });
    const body = await response.json().catch(() => null); setSaving(false);
    if (!response.ok) { toast.error(body?.error ?? "Could not save template copy"); return; }
    toast.success("Your template copy was saved");
    const refreshed = await fetch("/api/app/templates", { cache: "no-store" }); const data = await refreshed.json(); if (refreshed.ok) onSaved(data.current);
  }
  return <Card><CardHeader><CardTitle className="text-base">Customize your copy</CardTitle><p className="text-sm text-muted-foreground">These edits belong only to your agency. The platform template and other tenants are unchanged.</p></CardHeader><CardContent className="space-y-6">
    <div className="space-y-2"><Label htmlFor="copy-name">Template name</Label><Input id="copy-name" maxLength={120} value={name} onChange={(event) => setName(event.target.value)} /></div>
    <div className="space-y-3"><div className="flex items-center justify-between"><h3 className="text-sm font-semibold">Lead fields</h3><Button type="button" variant="outline" size="sm" onClick={() => setFields((items) => [...items, { field_key: `custom_field_${items.length + 1}`, label: "New field", type: "text", is_required: false, options: [], sort_order: items.length }])}>Add field</Button></div>{fields.map((field, index) => <div className="grid gap-2 sm:grid-cols-[140px_1fr_auto]" key={field.field_key}><Input aria-label={`${field.field_key} key`} value={field.field_key} readOnly /><Input aria-label={`${field.field_key} label`} maxLength={120} value={field.label} onChange={(event) => setFields((items) => items.map((item, itemIndex) => itemIndex === index ? { ...item, label: event.target.value } : item))} /><Button type="button" variant="ghost" onClick={() => setFields((items) => items.filter((_, itemIndex) => itemIndex !== index))}>Remove</Button></div>)}</div>
    <div className="space-y-3"><div className="flex items-center justify-between"><h3 className="text-sm font-semibold">Pipeline stages</h3><Button type="button" variant="outline" size="sm" onClick={() => setStages((items) => [...items, { stage_key: `custom_stage_${items.length + 1}`, label: "New stage", stage_type: "open", color: "#64748b", sort_order: items.length }])}>Add stage</Button></div>{stages.map((stage, index) => <div className="grid gap-2 sm:grid-cols-[140px_1fr_100px_auto]" key={stage.stage_key}><Input aria-label={`${stage.stage_key} key`} value={stage.stage_key} readOnly /><Input aria-label={`${stage.stage_key} label`} maxLength={120} value={stage.label} onChange={(event) => setStages((items) => items.map((item, itemIndex) => itemIndex === index ? { ...item, label: event.target.value } : item))} /><Input aria-label={`${stage.stage_key} color`} maxLength={7} value={stage.color} onChange={(event) => setStages((items) => items.map((item, itemIndex) => itemIndex === index ? { ...item, color: event.target.value } : item))} /><Button type="button" variant="ghost" onClick={() => setStages((items) => items.filter((_, itemIndex) => itemIndex !== index))}>Remove</Button></div>)}</div>
    <Button onClick={() => void save()} disabled={saving}>{saving ? "Saving…" : "Save my copy"}</Button>
  </CardContent></Card>;
}

export function TemplateSettings() {
  const [current, setCurrent] = useState<Current | null>(null); const [available, setAvailable] = useState<Available[]>([]); const [selected, setSelected] = useState(""); const [preview, setPreview] = useState<Preview | null>(null); const [loading, setLoading] = useState(true); const [applying, setApplying] = useState(false); const [error, setError] = useState("");
  async function load() { setLoading(true); const response = await fetch("/api/app/templates", { cache: "no-store" }); const body = await response.json().catch(() => null); setLoading(false); if (!response.ok) { setError(body?.error ?? "Could not load template settings"); return; } setCurrent(body.current); setAvailable(body.templates); }
  // Initial data is external server state; the effect intentionally hydrates this client view.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { void load(); }, []);
  const chosen = available.find((template) => `${template.id}:${template.version}` === selected);
  async function showPreview() { if (!chosen) return; const response = await fetch("/api/app/templates/preview", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ template_id: chosen.id, template_version: chosen.version }) }); const body = await response.json().catch(() => null); if (!response.ok) { toast.error(body?.error ?? "Could not preview template"); return; } setPreview(body.preview); }
  async function apply() { if (!chosen) return; setApplying(true); const response = await fetch("/api/app/templates", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ template_id: chosen.id, template_version: chosen.version }) }); const body = await response.json().catch(() => null); setApplying(false); if (!response.ok) { toast.error(body?.error ?? "Could not apply template"); return; } toast.success("Template applied to your workspace"); setPreview(null); await load(); }
  async function update() { if (!current?.latest) return; setSelected(`${current.latest.id}:${current.latest.version}`); const response = await fetch("/api/app/templates/preview", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ template_id: current.latest.id, template_version: current.latest.version }) }); const body = await response.json().catch(() => null); if (response.ok) setPreview(body.preview); }
  if (loading) return <p className="text-sm text-muted-foreground">Loading template settings…</p>; if (error) return <Card><CardContent className="p-6"><p className="text-sm text-destructive">{error}</p><Button className="mt-4" variant="outline" onClick={() => void load()}>Try again</Button></CardContent></Card>; if (!current) return null;
  return <div className="mx-auto max-w-6xl space-y-6"><div><h1 className="text-2xl font-extrabold tracking-tight">Template settings</h1><p className="mt-1 text-sm text-muted-foreground">Choose the starting point for your lead fields, pipeline and application form.</p></div>
    <Card><CardHeader><CardTitle className="text-base">Your active template</CardTitle></CardHeader><CardContent><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="font-semibold">{current.template.name}</p><p className="text-sm text-muted-foreground">{current.template.product_name} · {current.template.fields.length} fields · {current.template.stages.length} stages · version {current.assignment.template_version}</p></div>{current.latest && <Button variant="outline" onClick={() => void update()}>Review v{current.latest.version} update</Button>}</div>{current.latest && <p className="mt-3 text-sm text-amber-700">A newer version, “{current.latest.name}”, is available. Review its additions before choosing to apply it.</p>}</CardContent></Card>
    <Card><CardHeader><CardTitle className="text-base">Available templates</CardTitle><p className="text-sm text-muted-foreground">Only products included in your current subscription are shown.</p></CardHeader><CardContent className="space-y-4"><div className="grid gap-3 md:grid-cols-[1fr_auto_auto]"><select aria-label="Choose template" className="border-input bg-background h-9 rounded-md border px-3 text-sm" value={selected} onChange={(event) => { setSelected(event.target.value); setPreview(null); }}><option value="">Choose a template…</option>{available.map((template) => <option key={`${template.id}-${template.version}`} value={`${template.id}:${template.version}`}>{template.name} · {template.product_name} · v{template.version}</option>)}</select><Button variant="outline" disabled={!chosen} onClick={() => void showPreview()}>Preview changes</Button><Button disabled={!chosen || !preview || applying} onClick={() => void apply()}>{applying ? "Applying…" : "Confirm apply"}</Button></div>{chosen && preview && <div className="rounded-md border bg-muted/30 p-4 text-sm"><p className="font-semibold">Changes before commit</p>{preview.alreadyApplied && <p className="mt-2 text-green-700">This exact template version is already applied. Applying again is safe and will not duplicate anything.</p>}<p className="mt-2">Fields to add: {preview.fieldsToAdd.length ? preview.fieldsToAdd.join(", ") : "none"}</p><p>Stages to add: {preview.stagesToAdd.length ? preview.stagesToAdd.join(", ") : "none"}</p><p>Form sections to add: {preview.sectionsToAdd.length ? preview.sectionsToAdd.join(", ") : "none"}</p><p className="mt-2 text-muted-foreground">Existing customized fields and stages stay unchanged.</p></div>}{!available.length && <p className="text-sm text-muted-foreground">No templates are available for your subscription.</p>}</CardContent></Card>
    <TemplateEditor key={`${current.tenant_template_id}:${current.assignment.template_version}`} current={current} onSaved={setCurrent} />
    <div className="flex flex-wrap gap-2 text-xs text-muted-foreground"><Badge variant="outline">Tenant-owned copy</Badge><span className="self-center">Your changes apply only to this workspace.</span></div>
  </div>;
}
