// The fixed set of actions this app currently logs. Not exhaustive of what SA-0.3 lists — the
// rest (plan/price/subscription/invoice/payment/tenant-suspend events) don't exist until SA-1/2/3
// add the routes that produce them; add each one here as it lands.
export const AUDIT_ACTIONS = [
  "admin.login",
  "admin.created",
  "admin.updated",
  "tenant.created",
  "user.created",
  "user.invite_resent",
  "user.updated",
  "user.password_reset_sent",
  "user.email_change_requested",
  "user.activated",
  "user.deactivated",
  "user.suspended",
  "user.unsuspended",
  "feature.created",
  "feature.updated",
  "plan.created",
  "plan.updated",
  "plan.version_created",
  "plan.deleted",
  "subscription.assigned",
  "subscription.plan_changed",
  "subscription.cancelled",
  "subscription.paused",
  "subscription.resumed",
  "subscription.addon_attached",
  "subscription.addon_detached",
  "payment_provider.assigned",
  "payment_provider.simulator_set",
  "invoice.voided",
  "payment.recorded_manually",
  "coupon.created",
  "coupon.applied",
  "coupon.removed",
  "invoice.custom_created",
  "tenant.billing_mode_changed",
  "credit_note.requested",
  "credit_note.approved",
  "trial.extended",
  "trial.converted_early",
  "trial.cancelled",
  "trial.reminder_sent",
  "legal_document.published",
  "legal_document.reacceptance_cleared",
] as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[number];

export const AUDIT_ACTION_LABELS: Record<AuditAction, string> = {
  "admin.login": "Admin login",
  "admin.created": "Admin created",
  "admin.updated": "Admin updated",
  "tenant.created": "Tenant created",
  "user.created": "User created",
  "user.invite_resent": "Invitation resent",
  "user.updated": "User updated",
  "user.password_reset_sent": "Password reset sent",
  "user.email_change_requested": "Email change requested",
  "user.activated": "User activated",
  "user.deactivated": "User deactivated",
  "user.suspended": "User suspended",
  "user.unsuspended": "User unsuspended",
  "feature.created": "Feature created",
  "feature.updated": "Feature updated",
  "plan.created": "Plan created",
  "plan.updated": "Plan updated",
  "plan.version_created": "Plan version published",
  "plan.deleted": "Plan deleted",
  "subscription.assigned": "Subscription assigned",
  "subscription.plan_changed": "Plan changed",
  "subscription.cancelled": "Subscription cancelled",
  "subscription.paused": "Subscription paused",
  "subscription.resumed": "Subscription resumed",
  "subscription.addon_attached": "Add-on attached",
  "subscription.addon_detached": "Add-on detached",
  "payment_provider.assigned": "Payment provider assigned",
  "payment_provider.simulator_set": "Failure simulator changed",
  "invoice.voided": "Invoice voided",
  "payment.recorded_manually": "Payment recorded manually",
  "coupon.created": "Coupon created",
  "coupon.applied": "Coupon applied",
  "coupon.removed": "Coupon removed",
  "invoice.custom_created": "Custom invoice raised",
  "tenant.billing_mode_changed": "Billing mode changed",
  "credit_note.requested": "Credit note raised",
  "credit_note.approved": "Credit note approved",
  "trial.extended": "Trial extended",
  "trial.converted_early": "Trial converted early",
  "trial.cancelled": "Trial cancelled",
  "trial.reminder_sent": "Trial reminder sent",
  "legal_document.published": "Legal document published",
  "legal_document.reacceptance_cleared": "Re-acceptance requirement cleared",
};
