// The fixed set of actions this app currently logs. Not exhaustive of what SA-0.3 lists — the
// rest (plan/price/subscription/invoice/payment/tenant-suspend events) don't exist until SA-1/2/3
// add the routes that produce them; add each one here as it lands.
export const AUDIT_ACTIONS = [
  "admin.login",
  "admin.created",
  "admin.updated",
  "tenant.created",
  "user.created",
  "tenant.member_invited",
  "tenant.member_role_changed",
  "user.invite_resent",
  "user.updated",
  "user.password_reset_sent",
  "user.email_change_requested",
  "user.activated",
  "user.deactivated",
  "user.suspended",
  "user.unsuspended",
  "feature.created",
  "feature.updated",
  "feature.switch_changed",
  "plan.created",
  "plan.updated",
  "plan.version_created",
  "plan.deleted",
  "subscription.assigned",
  "subscription.plan_changed",
  "subscription.cancelled",
  "subscription.paused",
  "subscription.resumed",
  "subscription.addon_attached",
  "subscription.addon_detached",
  "payment_provider.assigned",
  "payment_provider.simulator_set",
  "invoice.voided",
  "payment.recorded_manually",
  "coupon.created",
  "coupon.applied",
  "coupon.removed",
  "offer.created",
  "offer.updated",
  "offer.applied",
  "product.created",
  "product.updated",
  "product.archived",
  "product.restored",
  "carrier.created",
  "carrier.updated",
  "carrier.archived",
  "carrier.restored",
  "tenant.carrier_configured",
  "tenant.commission_schedule_saved",
  "tenant.advance_rule_saved",
  "tenant.appointment_saved",
  "tenant.license_saved",
  "tenant.eo_policy_saved",
  "tenant.ce_record_saved",
  "tenant.contact_created",
  "tenant.contact_imported",
  "tenant.contact_merged",
  "tenant.contact_merge_undone",
  "tenant.contact_field_schema_saved",
  "tenant.partner_created",
  "tenant.partner_updated",
  "tenant.partner_term_added",
  "tenant.partner_lifecycle_changed",
  "template.created",
  "template.version_created",
  "template.duplicated",
  "template.archived",
  "template.restored",
  "invoice.custom_created",
  "tenant.billing_mode_changed",
  "setting.updated",
  "payment_provider.connection_tested",
  "compliance_vendor.created",
  "compliance_vendor.updated",
  "compliance_vendor.connection_tested",
  "credit_pack.created",
  "credit_pack.updated",
  "credit_pack.archived",
  "credit_pack.purchased",
  "meter_pricing.updated",
  "credit_grant.created",
  "maintenance.updated",
  "announcement.created",
  "announcement.updated",
  "announcement.deleted",
  "credit_note.requested",
  "credit_note.approved",
  "trial.extended",
  "trial.converted_early",
  "trial.cancelled",
  "trial.reminder_sent",
  "legal_document.published",
  "legal_document.reacceptance_cleared",
  // The period billing run raises invoices without a human choosing each amount, so the run itself
  // is the auditable act — who triggered it, what it billed, and what failed.
  "billing.period_run",
] as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[number];

export const AUDIT_ACTION_LABELS: Record<AuditAction, string> = {
  "admin.login": "Admin login",
  "admin.created": "Admin created",
  "admin.updated": "Admin updated",
  "tenant.created": "Tenant created",
  "user.created": "User created",
  "tenant.member_invited": "Tenant member invited",
  "tenant.member_role_changed": "Tenant member role changed",
  "user.invite_resent": "Invitation resent",
  "user.updated": "User updated",
  "user.password_reset_sent": "Password reset sent",
  "user.email_change_requested": "Email change requested",
  "user.activated": "User activated",
  "user.deactivated": "User deactivated",
  "user.suspended": "User suspended",
  "user.unsuspended": "User unsuspended",
  "feature.created": "Feature created",
  "feature.switch_changed": "Feature kill switch changed",
  "feature.updated": "Feature updated",
  "plan.created": "Plan created",
  "plan.updated": "Plan updated",
  "plan.version_created": "Plan version published",
  "plan.deleted": "Plan deleted",
  "subscription.assigned": "Subscription assigned",
  "subscription.plan_changed": "Plan changed",
  "subscription.cancelled": "Subscription cancelled",
  "subscription.paused": "Subscription paused",
  "subscription.resumed": "Subscription resumed",
  "subscription.addon_attached": "Add-on attached",
  "subscription.addon_detached": "Add-on detached",
  "payment_provider.assigned": "Payment provider assigned",
  "payment_provider.simulator_set": "Failure simulator changed",
  "invoice.voided": "Invoice voided",
  "payment.recorded_manually": "Payment recorded manually",
  "coupon.created": "Coupon created",
  "coupon.applied": "Coupon applied",
  "coupon.removed": "Coupon removed",
  "offer.created": "Offer created",
  "offer.updated": "Offer updated",
  "offer.applied": "Offer applied",
  "product.created": "Product created",
  "product.updated": "Product updated",
  "product.archived": "Product archived",
  "product.restored": "Product restored",
  "carrier.created": "Carrier created",
  "carrier.updated": "Carrier updated",
  "carrier.archived": "Carrier archived",
  "carrier.restored": "Carrier restored",
  "tenant.carrier_configured": "Carrier contract configured",
  "tenant.commission_schedule_saved": "Commission schedule saved",
  "tenant.advance_rule_saved": "Advance rule saved",
  "tenant.appointment_saved": "Appointment saved",
  "tenant.license_saved": "Licence saved",
  "tenant.eo_policy_saved": "E&O policy saved",
  "tenant.ce_record_saved": "Continuing education record saved",
  "tenant.contact_created": "Contact created",
  "tenant.contact_imported": "Contact imported",
  "tenant.contact_merged": "Contacts merged",
  "tenant.contact_merge_undone": "Contact merge undone",
  "tenant.contact_field_schema_saved": "Contact field schema saved",
  "tenant.partner_created": "Partner created",
  "tenant.partner_updated": "Partner updated",
  "tenant.partner_term_added": "Partner terms added",
  "tenant.partner_lifecycle_changed": "Partner lifecycle changed",
  "template.created": "Template created",
  "template.version_created": "Template version created",
  "template.duplicated": "Template duplicated",
  "template.archived": "Template archived",
  "template.restored": "Template restored",
  "invoice.custom_created": "Custom invoice raised",
  "setting.updated": "Setting changed",
  "payment_provider.connection_tested": "Provider connection tested",
  "compliance_vendor.created": "Compliance vendor created",
  "compliance_vendor.updated": "Compliance vendor updated",
  "compliance_vendor.connection_tested": "Compliance vendor connection tested",
  "credit_pack.created": "Credit pack created",
  "credit_pack.updated": "Credit pack updated",
  "credit_pack.archived": "Credit pack archived",
  "credit_pack.purchased": "Credit pack added to invoice",
  "meter_pricing.updated": "Meter pricing changed",
  "credit_grant.created": "Credits granted",
  "maintenance.updated": "Maintenance mode changed",
  "announcement.created": "Announcement created",
  "announcement.updated": "Announcement updated",
  "announcement.deleted": "Announcement deleted",
  "tenant.billing_mode_changed": "Billing mode changed",
  "credit_note.requested": "Credit note raised",
  "credit_note.approved": "Credit note approved",
  "trial.extended": "Trial extended",
  "trial.converted_early": "Trial converted early",
  "trial.cancelled": "Trial cancelled",
  "trial.reminder_sent": "Trial reminder sent",
  "legal_document.published": "Legal document published",
  "legal_document.reacceptance_cleared": "Re-acceptance requirement cleared",
  "billing.period_run": "Period billing run",
};
