// The fixed set of actions this app currently logs. Not exhaustive of what SA-0.3 lists — the
// rest (plan/price/subscription/invoice/payment/tenant-suspend events) don't exist until SA-1/2/3
// add the routes that produce them; add each one here as it lands.
export const AUDIT_ACTIONS = [
  "admin.login",
  "admin.logout",
  "security.login_unlocked",
  "admin.created",
  "admin.updated",
  "tenant.created",
  "user.created",
  "tenant.member_invited",
  "tenant.member_role_changed",
  "tenant.member_invite_resent",
  "tenant.member_invite_revoked",
  "tenant.member_licensed_states_changed",
  // Admin tenant record › Users & seats. Staff revoking an invite reuse tenant.member_invite_revoked
  // (actor_type admin); these two are the bulk revoke and the people export.
  "tenant.stale_invites_revoked",
  "tenant.users_exported",
  "user.invite_resent",
  "user.updated",
  "user.password_reset_sent",
  "user.password_reset_requested",
  "user.email_change_requested",
  "user.activated",
  "user.deactivated",
  "user.suspended",
  "user.unsuspended",
  "user.sessions_revoked",
  // SA-1.4 soft delete. The row stays in audit_log for good, which is the point: it is the only
  // durable record of who removed an account and when the recovery window closed.
  "user.deleted",
  "feature.created",
  "feature.updated",
  "feature.switch_changed",
  // Per-tenant feature overrides (20260924344000). Target is the tenant; the feature is in metadata.
  "tenant.feature_override_set",
  "tenant.feature_override_removed",
  "addon.created",
  "addon.updated",
  "addon.archived",
  "plan.created",
  "plan.updated",
  "plan.version_created",
  "plan.deleted",
  "subscription.assigned",
  "subscription.plan_changed",
  "subscription.cancelled",
  "subscription.paused",
  "subscription.resumed",
  "subscription.addon_attached",
  "subscription.addon_detached",
  "payment_provider.assigned",
  "payment_provider.simulator_set",
  "invoice.voided",
  "payment.recorded_manually",
  "coupon.created",
  "coupon.applied",
  "coupon.removed",
  // Deactivation switches the Whop promo code off first (fail closed). A refused attempt is its own
  // row, so "who tried to switch this code off, and why did it not happen" has an answer.
  "coupon.deactivated",
  "coupon.deactivation_failed",
  "offer.created",
  "offer.updated",
  "offer.applied",
  "product.created",
  "product.updated",
  "product.archived",
  "product.restored",
  "carrier.created",
  "carrier.updated",
  "carrier.archived",
  "carrier.restored",
  // A super admin deactivated a platform carrier tenants still use (20260924357000). Reason required.
  "carrier.deactivated_in_use",
  "tenant.carrier_configured",
  "tenant.commission_schedule_saved",
  "tenant.advance_rule_saved",
  "tenant.appointment_saved",
  "tenant.appointment_outcome_recorded",
  "tenant.license_saved",
  "tenant.eo_policy_saved",
  "tenant.ce_record_saved",
  "tenant.carrier_training_added",
  "tenant.carrier_training_completed",
  "tenant.carrier_training_removed",
  "tenant.contact_created",
  "tenant.contact_imported",
  "tenant.contact_merged",
  "tenant.contact_merge_undone",
  "tenant.contact_duplicate_dismissed",
  "tenant.contact_field_schema_saved",
  "tenant.partner_created",
  "tenant.partner_chat_message_sent",
  "tenant.partner_message_posted",
  "tenant.partner_chat_read",
  "tenant.partner_notification_settings_updated",
  "tenant.agent_partner_chat_message_sent",
  "tenant.partner_chat_channel_created",
  "tenant.partner_chat_channel_archived",
  "tenant.partner_chat_channel_restored",
  "tenant.partner_system_card_posted",
  "tenant.partner_updated",
  "tenant.partner_timezone_updated",
  "tenant.consent_evidence_exported",
  "tenant.dial_refused",
  "tenant.dial_walk_recorded",
  "tenant.callback_refused",
  "tenant.partner_sessions_revoked",
  "tenant.partner_term_added",
  "tenant.partner_lifecycle_changed",
  "tenant.partner_user_invited",
  "tenant.partner_user_invite_resent",
  "tenant.partner_user_deactivated",
  "tenant.partner_user_reactivated",
  "tenant.partner_user_accepted",
  "tenant.partner_user_admin_assigned",
  "tenant.partner_form_profile_saved",
  "tenant.partner_form_catalog_field_added",
  "tenant.partner_form_catalog_field_updated",
  "tenant.partner_form_catalog_field_deleted",
  "tenant.partner_form_preset_saved",
  "tenant.partner_form_preset_archived",
  "tenant.partner_market_access_saved",
  "tenant.product_enabled",
  "tenant.product_disabled",
  "tenant.partner_product_approved",
  "tenant.partner_product_revoked",
  "tenant.form_definition_saved",
  "tenant.form_draft_saved",
  "tenant.form_draft_cleared",
  "tenant.partner_lead_submitted",
  "tenant.partner_submission_rejected",
  "tenant.partner_lead_duplicate_detected",
  "tenant.partner_lead_duplicate_overridden",
  "tenant.intake_failure_recording_failed",
  // An owner put a partner lead back in the inbox after its queue insert failed at intake.
  "tenant.intake_work_item_recovered",
  "tenant.lead_signature_readiness_updated",
  "tenant.affiliate_link_created",
  "tenant.affiliate_link_updated",
  "tenant.pipeline_created",
  "tenant.pipeline_updated",
  "tenant.policy_created",
  "tenant.policies_imported",
  "tenant.policy_updated",
  "tenant.lapse_signal_recorded",
  "tenant.lapse_signals_resolved",
  "tenant.pipeline_deleted",
  "tenant.pipeline_stage_created",
  "tenant.pipeline_stage_updated",
  "tenant.pipeline_stage_archived",
  "tenant.pipeline_reordered",
  "tenant.stage_disposition_mapped",
  "tenant.stage_disposition_removed",
  "tenant.lead_stage_changed",
  "tenant.lead_preflight_rechecked",
  "tenant.lead_note_created",
  "tenant.lead_note_updated",
  "tenant.lead_note_deleted",
  "tenant.transfer_claimed",
  "tenant.transfer_claim_chat_failed",
  "tenant.disposition_partner_card_failed",
  "tenant.buffer_handoff_offered",
  "tenant.buffer_handoff_accepted",
  "tenant.buffer_handoff_returned",
  "tenant.verification_field_updated",
  "tenant.verification_field_revealed",
  "tenant.dispositioned",
  "tenant.agent_presence_updated",
  "tenant.agent_floor_nudged",
  "tenant.callback_scheduled",
  "tenant.callback_rescheduled",
  "tenant.callback_cancelled",
  "tenant.callback_completed",
  "tenant.callback_missed",
  "tenant.callback_replaced",
  "tenant.queue_sla_settings_updated",
  "tenant.agent_notification_settings_updated",
  "tenant.own_profile_updated",
  "tenant.workspace_switched",
  "tenant.lead_sla_warned",
  "tenant.lead_sla_escalated",
  "tenant.lead_sla_partner_notified",
  "tenant.lead_sla_expired",
  "tenant.lead_sla_reopened",
  "tenant.deal_flow_created",
  "tenant.deal_flow_updated",
  "tenant.policy_marked_issued",
  "tenant.policy_marked_lapsed",
  "template.created",
  "template.version_created",
  "template.duplicated",
  "template.archived",
  "template.restored",
  "template.published",
  "invoice.custom_created",
  "tenant.billing_mode_changed",
  "tenant.suspended",
  "tenant.unsuspended",
  "setting.updated",
  "payment_provider.connection_tested",
  "compliance_vendor.created",
  "compliance_vendor.updated",
  "compliance_vendor.connection_tested",
  "credit_pack.created",
  "credit_pack.updated",
  "credit_pack.archived",
  "credit_pack.purchased",
  "meter_pricing.updated",
  "credit_grant.created",
  "maintenance.updated",
  "announcement.created",
  "announcement.updated",
  "announcement.deleted",
  "credit_note.requested",
  "credit_note.approved",
  "credit_note.reconciled",
  "trial.extended",
  "trial.converted_early",
  "trial.cancelled",
  "trial.reminder_sent",
  "legal_document.published",
  "legal_document.reacceptance_cleared",
  // Unpublished drafts (20260924363000). Never read by a customer surface; publishing one writes
  // legal_document.published like the direct publish does, with metadata.fromDraft = true.
  "legal_document.draft_saved",
  "legal_document.draft_discarded",
  // The period billing run raises invoices without a human choosing each amount, so the run itself
  // is the auditable act — who triggered it, what it billed, and what failed.
  "billing.period_run",
  "billing.waiver_granted",
  "billing.waiver_revoked",
  "tenant.import_mapping_saved",
  "tenant.lead_import_scrub_rejected",
  "tenant.lead_vendor_saved",
  "tenant.appointment_booked",
  "tenant.appointment_rescheduled",
  "tenant.appointment_rebooked",
  "tenant.calendar_updated",
  "tenant.calendar_linked",
  "tenant.calendar_unlinked",
  "tenant.cadence_updated",
  "tenant.phone_suppressed",
  "tenant.calling_window_updated",
  "tenant.post_key_minted",
  "tenant.post_key_rotated",
  "tenant.post_key_updated",
  "tenant.lead_import_committed",
  // A reviewed import that added the file's cost to its campaign (20260924330100), in the same
  // transaction as the leads.
  "tenant.campaign_spend_added_by_import",
  // Campaigns concept audit: an owner's re-screen of a whole campaign (20260925706100), and a
  // campaign's status, cost, weight or test-batch flag changed from /app/campaigns.
  "tenant.campaign_scrub_started",
  "tenant.campaign_scrub_finished",
  "tenant.campaign_updated",
  // A whole list assigned in one transaction (assign_lead_list, 20260924342000). Written by the SQL
  // function itself, in the same transaction as the moves, with the rule chain as published.
  "tenant.lead_list_assigned",
  // Lead recycling (20260925706500). Both written by SQL: reactivate_nurture when a batch starts,
  // complete_nurture_reactivation when its last lead is screened.
  "tenant.recycle_batch_started",
  "tenant.recycle_batch_completed",
  // Lead assignment (20260925702100 / 702200). The first three are written by SQL functions: a
  // posted lead routed on arrival, one left in the pool, and an owned lead returned because the
  // owner's own licence in its state lapsed. The last is the owner turning routing on arrival on/off.
  "tenant.lead_auto_routed",
  "tenant.lead_auto_route_skipped",
  "tenant.lead_returned_licence_lapsed",
  "tenant.assignment_auto_route_changed",
  // A claim drafted from a list's import removals (create_import_removal_claim, 20260925703200).
  // Written by the SQL function in the same transaction as the claim.
  "tenant.vendor_claim_drafted_from_import",
  // One claim per campaign from Vendor returns' preview: lead rows and import removals together,
  // only the reasons left on (create_combined_vendor_return_claim, 20260925707500). Written by the
  // SQL function in the same transaction as the claim.
  "tenant.vendor_claim_drafted",
  "tenant.queue_scoring_updated",
  "tenant.agency_profile_saved",
  "tenant.partner_support_contact_saved",
  // Carrier commission statements (20260924260000). Import proposes; only a person's acceptance or
  // manual match posts a line to the ledger, so each decision is its own row.
  "tenant.commission_statement_imported",
  "tenant.statement_mapping_saved",
  "tenant.statement_match_accepted",
  "tenant.statement_match_rejected",
  "tenant.statement_line_matched",
  "tenant.statement_line_left_unmatched",
  "tenant.commission_statement_voided",
  "state_disclosure.published",
  "state_disclosure.updated",
  "state_disclosure.withdrawn",
  "state_disclosure.proposed",
  "state_disclosure.pack_imported",
  "state_disclosure.proposal_approved",
  "state_disclosure.proposal_rejected",
  "state_disclosure.proposal_cancelled",
] as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[number];

export const AUDIT_ACTION_LABELS: Record<AuditAction, string> = {
  "admin.login": "Admin login",
  "admin.logout": "Admin sign-out",
  "security.login_unlocked": "Login lockout cleared",
  "admin.created": "Admin created",
  "admin.updated": "Admin updated",
  "tenant.created": "Tenant created",
  "user.created": "User created",
  "tenant.member_invited": "Tenant member invited",
  "tenant.member_role_changed": "Tenant member role changed",
  "tenant.member_invite_resent": "Tenant member invitation resent",
  "tenant.member_invite_revoked": "Tenant member invitation revoked",
  "tenant.member_licensed_states_changed": "Tenant member licensed states changed",
  "tenant.stale_invites_revoked": "Expired tenant invitations revoked by staff",
  "tenant.users_exported": "Tenant people exported to CSV (names and emails)",
  "user.invite_resent": "Invitation resent",
  "user.updated": "User updated",
  "user.password_reset_sent": "Password reset sent",
  "user.password_reset_requested": "Password reset requested by the user",
  "user.email_change_requested": "Email change requested",
  "user.activated": "User activated",
  "user.deactivated": "User deactivated",
  "user.suspended": "User suspended",
  "user.unsuspended": "User unsuspended",
  "user.sessions_revoked": "Signed out of every session by staff",
  "user.deleted": "User deleted",
  "feature.created": "Feature created",
  "feature.switch_changed": "Feature kill switch changed",
  "tenant.feature_override_set": "Feature switched on or off for one tenant",
  "tenant.feature_override_removed": "Feature override removed; the tenant is back on the plan",
  "feature.updated": "Feature updated",
  "addon.created": "Add-on created",
  "addon.updated": "Add-on updated",
  "addon.archived": "Add-on archived",
  "plan.created": "Plan created",
  "plan.updated": "Plan updated",
  "plan.version_created": "Plan version published",
  "plan.deleted": "Plan deleted",
  "subscription.assigned": "Subscription assigned",
  "subscription.plan_changed": "Plan changed",
  "subscription.cancelled": "Subscription cancelled",
  "subscription.paused": "Subscription paused",
  "subscription.resumed": "Subscription resumed",
  "subscription.addon_attached": "Add-on attached",
  "subscription.addon_detached": "Add-on detached",
  "payment_provider.assigned": "Payment provider assigned",
  "payment_provider.simulator_set": "Failure simulator changed",
  "invoice.voided": "Invoice voided",
  "payment.recorded_manually": "Payment recorded manually",
  "coupon.created": "Coupon created",
  "coupon.applied": "Coupon applied",
  "coupon.removed": "Coupon removed",
  "coupon.deactivated": "Coupon deactivated",
  "coupon.deactivation_failed": "Coupon deactivation did not complete",
  "offer.created": "Offer created",
  "offer.updated": "Offer updated",
  "offer.applied": "Offer applied",
  "product.created": "Product created",
  "product.updated": "Product updated",
  "product.archived": "Product archived",
  "product.restored": "Product restored",
  "carrier.created": "Carrier created",
  "carrier.updated": "Carrier updated",
  "carrier.archived": "Carrier deactivated",
  "carrier.restored": "Carrier reactivated",
  "carrier.deactivated_in_use": "Carrier deactivated while tenants still use it (super admin override)",
  "tenant.carrier_configured": "Carrier contract configured",
  "tenant.commission_schedule_saved": "Commission schedule saved",
  "tenant.advance_rule_saved": "Advance rule saved",
  "tenant.appointment_saved": "Appointment saved",
  "tenant.appointment_outcome_recorded": "Appointment outcome recorded",
  "tenant.license_saved": "Licence saved",
  "tenant.eo_policy_saved": "E&O policy saved",
  "tenant.ce_record_saved": "Continuing education record saved",
  "tenant.carrier_training_added": "Carrier training added",
  "tenant.carrier_training_completed": "Carrier training marked complete",
  "tenant.carrier_training_removed": "Carrier training removed",
  "tenant.contact_created": "Contact created",
  "tenant.contact_imported": "Contact imported",
  "tenant.contact_merged": "Contacts merged",
  "tenant.contact_merge_undone": "Contact merge undone",
  "tenant.contact_duplicate_dismissed": "Duplicate match dismissed",
  "tenant.contact_field_schema_saved": "Contact field schema saved",
  "tenant.partner_created": "Partner created",
  "tenant.partner_chat_message_sent": "Partner chat message sent",
  "tenant.partner_message_posted": "Partner message posted",
  "tenant.partner_chat_read": "Partner chat marked read",
  "tenant.partner_notification_settings_updated":
    "Partner notification settings updated",
  "tenant.agent_partner_chat_message_sent": "Agent partner chat message sent",
  "tenant.partner_chat_channel_created": "Partner chat channel created",
  "tenant.partner_chat_channel_archived": "Chat channel archived",
  "tenant.partner_chat_channel_restored": "Chat channel restored",
  "tenant.partner_system_card_posted": "Partner system card posted",
  "tenant.partner_updated": "Partner updated",
  "tenant.partner_timezone_updated": "Partner timezone changed",
  "tenant.consent_evidence_exported": "Consent evidence exported",
  "tenant.dial_refused": "Dial refused by screening",
  "tenant.dial_walk_recorded": "Call outcome questions recorded against a dial",
  "tenant.callback_refused": "Callback time refused",
  "tenant.partner_sessions_revoked": "Partner signed out other sessions",
  "tenant.partner_term_added": "Partner terms added",
  "tenant.partner_lifecycle_changed": "Partner lifecycle changed",
  "tenant.partner_user_invited": "Partner user invited",
  "tenant.partner_user_invite_resent": "Partner user invitation resent",
  "tenant.partner_user_deactivated": "Partner user deactivated",
  "tenant.partner_user_reactivated": "Partner user reactivated",
  "tenant.partner_user_accepted": "Partner user accepted invitation",
  "tenant.partner_user_admin_assigned":
    "Partner user assigned to partner admin",
  "tenant.partner_form_profile_saved": "Partner form profile saved",
  "tenant.partner_form_catalog_field_added": "Partner form catalog field added",
  "tenant.partner_form_catalog_field_updated": "Partner form catalog field updated",
  "tenant.partner_form_catalog_field_deleted": "Partner form catalog field deleted",
  "tenant.partner_form_preset_saved": "Partner form preset saved",
  "tenant.partner_form_preset_archived": "Partner form preset archived",
  "tenant.partner_market_access_saved": "Partner market access saved",
  "tenant.product_enabled": "Tenant product enabled",
  "tenant.product_disabled": "Tenant product disabled",
  "tenant.partner_product_approved": "Partner product approved",
  "tenant.partner_product_revoked": "Partner product approval revoked",
  "tenant.form_definition_saved": "Dynamic form saved",
  "tenant.form_draft_saved": "Form draft saved",
  "tenant.form_draft_cleared": "Form draft cleared",
  "tenant.partner_lead_submitted": "Partner lead submitted",
  "tenant.partner_submission_rejected": "Partner submission rejected",
  "tenant.partner_lead_duplicate_detected": "Partner lead duplicate detected",
  "tenant.partner_lead_duplicate_overridden":
    "Partner lead duplicate overridden",
  "tenant.intake_failure_recording_failed": "Intake failure recording failed",
  "tenant.intake_work_item_recovered": "Lost transfer recovered into the inbox",
  "tenant.lead_signature_readiness_updated": "Signature availability updated on a lead",
  "tenant.affiliate_link_created": "Affiliate link created",
  "tenant.affiliate_link_updated": "Affiliate link updated",
  "tenant.pipeline_created": "Pipeline created",
  "tenant.pipeline_updated": "Pipeline updated",
  "tenant.policy_created": "Policy created",
  "tenant.policies_imported": "Policies imported",
  "tenant.policy_updated": "Policy updated",
  "tenant.lapse_signal_recorded": "Lapse signal recorded on a policy (missed draft, returned payment, service call or other)",
  "tenant.lapse_signals_resolved": "A policy's open lapse signals resolved (payment received, reinstated, lapsed or false alarm)",
  "tenant.pipeline_deleted": "Pipeline deleted",
  "tenant.pipeline_stage_created": "Pipeline stage created",
  "tenant.pipeline_stage_updated": "Pipeline stage updated",
  "tenant.pipeline_stage_archived": "Pipeline stage archived",
  "tenant.pipeline_reordered": "Pipeline reordered",
  "tenant.stage_disposition_mapped": "Stage disposition mapped",
  "tenant.stage_disposition_removed": "Stage disposition removed",
  "tenant.lead_stage_changed": "Lead stage changed",
  "tenant.lead_preflight_rechecked": "Existing-customer pre-flight rechecked",
  "tenant.lead_note_created": "Lead note created",
  "tenant.lead_note_updated": "Lead note updated",
  "tenant.lead_note_deleted": "Lead note deleted",
  "tenant.transfer_claimed": "Transfer claimed",
  "tenant.transfer_claim_chat_failed": "Transfer claim partner update failed",
  "tenant.disposition_partner_card_failed": "Disposition partner outcome update failed",
  "tenant.buffer_handoff_offered": "Buffer handoff offered",
  "tenant.buffer_handoff_accepted": "Buffer handoff accepted",
  "tenant.buffer_handoff_returned": "Buffer handoff returned",
  "tenant.verification_field_updated": "Verification field updated",
  "tenant.verification_field_revealed": "Sensitive verification field revealed",
  "tenant.dispositioned": "Call dispositioned",
  "tenant.agent_presence_updated": "Agent availability updated",
  "tenant.agent_floor_nudged": "Agent Floor nudge sent",
  "tenant.callback_scheduled": "Callback scheduled",
  "tenant.callback_rescheduled": "Callback rescheduled",
  "tenant.callback_cancelled": "Callback cancelled",
  "tenant.callback_completed": "Callback completed",
  "tenant.callback_missed": "Callback missed",
  "tenant.callback_replaced": "Callback replaced by a new booking",
  "tenant.queue_sla_settings_updated": "Queue SLA settings updated",
  "tenant.agent_notification_settings_updated":
    "Agent notification settings updated",
  "tenant.own_profile_updated": "Own profile updated",
  "tenant.workspace_switched": "Switched workspace",
  "tenant.lead_sla_warned": "Lead SLA warning fired",
  "tenant.lead_sla_escalated": "Lead SLA escalated",
  "tenant.lead_sla_partner_notified": "Partner notified of unclaimed lead",
  "tenant.lead_sla_expired": "Unclaimed lead expired",
  "tenant.lead_sla_reopened": "Expired lead reopened",
  "tenant.deal_flow_created": "Manual deal-flow row created",
  "tenant.deal_flow_updated": "Deal-flow row updated",
  "tenant.policy_marked_issued": "Policy marked issued on a deal",
  "tenant.policy_marked_lapsed": "Issued policy marked lapsed",
  "template.created": "Template created",
  "template.version_created": "Template version created",
  "template.duplicated": "Template duplicated",
  "template.archived": "Template archived",
  "template.restored": "Template restored",
  "template.published": "Template draft published",
  "invoice.custom_created": "Custom invoice raised",
  "setting.updated": "Setting changed",
  "payment_provider.connection_tested": "Provider connection tested",
  "compliance_vendor.created": "Compliance vendor created",
  "compliance_vendor.updated": "Compliance vendor updated",
  "compliance_vendor.connection_tested": "Compliance vendor connection tested",
  "credit_pack.created": "Credit pack created",
  "credit_pack.updated": "Credit pack updated",
  "credit_pack.archived": "Credit pack archived",
  "credit_pack.purchased": "Credit pack added to invoice",
  "meter_pricing.updated": "Meter pricing changed",
  "credit_grant.created": "Credits granted",
  "maintenance.updated": "Maintenance mode changed",
  "announcement.created": "Announcement created",
  "announcement.updated": "Announcement updated",
  "announcement.deleted": "Announcement deleted",
  "tenant.billing_mode_changed": "Billing mode changed",
  "tenant.suspended": "Agency suspended",
  "tenant.unsuspended": "Agency unsuspended",
  "credit_note.requested": "Credit note raised",
  "credit_note.approved": "Credit note approved",
  "credit_note.reconciled": "Credit note reconciled",
  "trial.extended": "Trial extended",
  "trial.converted_early": "Trial converted early",
  "trial.cancelled": "Trial cancelled",
  "trial.reminder_sent": "Trial reminder sent",
  "legal_document.published": "Legal document published",
  "legal_document.reacceptance_cleared": "Re-acceptance requirement cleared",
  "legal_document.draft_saved": "Legal document draft saved (not visible to customers)",
  "legal_document.draft_discarded": "Legal document draft discarded",
  "billing.period_run": "Period billing run",
  "billing.waiver_granted": "Overage waiver granted",
  "billing.waiver_revoked": "Overage waiver revoked",
  "tenant.import_mapping_saved": "Import mapping saved",
  "tenant.lead_import_scrub_rejected": "Purchased leads rejected at scrub",
  "tenant.lead_vendor_saved": "Lead vendor created or updated",
  "tenant.appointment_booked": "Appointment booked on an agent calendar",
  "tenant.appointment_rescheduled": "Appointment rescheduled",
  "tenant.appointment_rebooked": "No-show rebooked as a new appointment",
  "tenant.calendar_updated": "Working hours, blocked time or booking policy changed",
  "tenant.calendar_linked": "A Google or Outlook calendar was linked to an agent's availability",
  "tenant.calendar_unlinked": "A linked Google or Outlook calendar was removed from an agent's availability",
  "tenant.cadence_updated": "Dialing cadence changed for the tenant or one campaign",
  "tenant.recycle_batch_started": "A recycle batch was started with a new angle; its leads wait for a fresh screening",
  "tenant.recycle_batch_completed": "Every lead in a recycle batch was screened; cleared ones went back to the dialer",
  "tenant.phone_suppressed": "A phone number was added to a do-not-call list, permanently",
  "tenant.calling_window_updated": "Calling hours narrowed or cleared, for the agency or one campaign",
  "tenant.post_key_minted": "A lead-posting key was created for a vendor",
  "tenant.post_key_rotated": "A lead-posting key was rotated and the old one retired",
  "tenant.post_key_updated": "A lead-posting key was enabled, disabled, or its field map changed",
  "tenant.lead_import_committed": "Lead import committed after review",
  "tenant.campaign_spend_added_by_import": "A list import added its cost and rows purchased to the campaign's spend",
  "tenant.campaign_scrub_started": "A campaign re-scrub was started or resumed; its leads stop being served until it ends",
  "tenant.campaign_scrub_finished": "A campaign re-scrub ended, scrubbed or failed",
  "tenant.campaign_updated": "A campaign's status, cost, mixing weight or test-batch flag was changed",
  "tenant.lead_list_assigned": "A lead list's unassigned leads were assigned in one transaction",
  "tenant.lead_auto_routed": "A posted lead was routed on arrival by a real-time rule",
  "tenant.lead_auto_route_skipped": "A posted lead could not be routed on arrival and stayed in the pool",
  "tenant.lead_returned_licence_lapsed": "An owned lead returned to the pool because the owner's licence in its state lapsed",
  "tenant.assignment_auto_route_changed": "Routing posted leads on arrival turned on or off",
  "tenant.vendor_claim_drafted_from_import": "A vendor credit claim was drafted from a list's import removals",
  "tenant.vendor_claim_drafted": "A vendor credit claim was drafted for a campaign on Vendor returns",
  "tenant.queue_scoring_updated":"Queue scoring settings or weights changed",
  "tenant.agency_profile_saved": "Agency legal identity changed (a dated history row is kept)",
  "tenant.partner_support_contact_saved": "Support email or phone shown to partners changed",
  "tenant.commission_statement_imported": "Carrier commission statement imported for review (nothing posted yet)",
  "tenant.statement_mapping_saved": "Carrier statement column mapping remembered",
  "tenant.statement_match_accepted": "Statement line match accepted; the line posts to the commission ledger",
  "tenant.statement_match_rejected": "Proposed statement line match rejected",
  "tenant.statement_line_matched": "Statement line matched to a policy by hand; the line posts to the commission ledger",
  "tenant.statement_line_left_unmatched": "Statement line left unmatched on purpose",
  "tenant.commission_statement_voided": "Carrier commission statement voided; its lines leave the commission ledger",
  "state_disclosure.published": "Required call disclosure published for one or more states",
  "state_disclosure.updated": "Required call disclosure wording or effective date changed",
  "state_disclosure.withdrawn": "Required call disclosure withdrawn",
  "state_disclosure.proposed": "New call disclosure wording proposed for review",
  "state_disclosure.pack_imported": "Disclosure pack imported as proposals for review",
  "state_disclosure.proposal_approved": "Proposed call disclosure approved and published",
  "state_disclosure.proposal_rejected": "Proposed call disclosure rejected",
  "state_disclosure.proposal_cancelled": "Proposed call disclosure withdrawn by its author",
};
