/**
 * Reconstructs the live `public` schema from the Postgres catalog and writes the objects that no
 * committed migration creates.
 *
 * Backlog #29: migrations in this repo start at 0001, which is SA-4.1. Everything SA-0 through SA-3
 * built — tenants, users, plans, subscriptions, invoices, payments, credit_notes, the audit log —
 * exists only inside the live Supabase project. A fresh clone compiles and dies at runtime, the
 * REVOKEs that make the audit log append-only have never appeared in a diff, and there is nothing
 * to roll back to.
 *
 * `supabase db pull` would be the obvious tool and cannot be used here: the only credential this
 * repo has is TENANT_DB_URL, whose role is deliberately NOBYPASSRLS with no DDL rights, and the
 * Supabase CLI wants an owner connection. Catalog reads, however, are open to every role — which is
 * enough to rebuild the schema exactly.
 *
 * What it emits, in dependency order: extensions, enums, tables (columns, defaults, identity),
 * primary/unique/check constraints, foreign keys, indexes, views, functions, triggers, RLS state,
 * policies, and the full grant/revoke picture.
 *
 * The grants matter as much as the tables. Tenant isolation in this codebase is not enforced by
 * application code — it is `tenant_app` being NOBYPASSRLS plus a policy per table. A baseline that
 * restored the tables and lost the policies would look correct and be wide open.
 *
 *   node --env-file=.env.local scripts/dump-schema.mjs            # writes the baseline
 *   node --env-file=.env.local scripts/dump-schema.mjs --full     # everything, ignoring migrations
 *   node --env-file=.env.local scripts/dump-schema.mjs --stdout   # print instead of write
 */
import pg from "pg";
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import process from "node:process";

const MIGRATIONS_DIR = "supabase/migrations";
const OUT = join(MIGRATIONS_DIR, "0000_baseline.sql");
const full = process.argv.includes("--full");
const toStdout = process.argv.includes("--stdout");

if (!process.env.TENANT_DB_URL) {
  console.error("TENANT_DB_URL is not set. Run with --env-file=.env.local");
  process.exit(1);
}

/** Objects any committed migration already creates — the baseline must not duplicate them. */
function alreadyMigrated() {
  const names = { tables: new Set(), functions: new Set(), indexes: new Set(), triggers: new Set(), types: new Set() };
  if (full) return names;
  for (const file of readdirSync(MIGRATIONS_DIR).filter((f) => f.endsWith(".sql") && f !== "0000_baseline.sql")) {
    const sql = readFileSync(join(MIGRATIONS_DIR, file), "utf8");
    const grab = (re, bucket) => {
      for (const m of sql.matchAll(re)) {
        names[bucket].add(m[1].replace(/^public\./i, "").replace(/"/g, "").toLowerCase());
      }
    };
    grab(/create\s+table\s+(?:if\s+not\s+exists\s+)?([\w".]+)/gi, "tables");
    grab(/create\s+(?:or\s+replace\s+)?function\s+([\w".]+)/gi, "functions");
    grab(/create\s+(?:unique\s+)?index\s+(?:concurrently\s+)?(?:if\s+not\s+exists\s+)?([\w".]+)/gi, "indexes");
    grab(/create\s+(?:or\s+replace\s+)?trigger\s+([\w".]+)/gi, "triggers");
    grab(/create\s+type\s+([\w".]+)/gi, "types");
  }
  return names;
}

const skip = alreadyMigrated();
const client = new pg.Client({ connectionString: process.env.TENANT_DB_URL, ssl: { rejectUnauthorized: false } });
await client.connect();
const q = async (sql, params = []) => (await client.query(sql, params)).rows;

/**
 * Objects that belong to an extension rather than to us.
 *
 * pg_trgm is installed into `public`, so a naive catalog dump claims authorship of thirty-odd
 * gtrgm_/word_similarity_ functions and their operator types. `create extension` already creates
 * those; re-declaring them makes the baseline fail on a fresh database. pg_depend marks them with
 * deptype 'e'.
 */
async function extensionMembers(catalog) {
  const rows = await q(
    "select objid from pg_depend where deptype = 'e' and classid = $1::regclass",
    [catalog],
  );
  return new Set(rows.map((r) => Number(r.objid)));
}
const extFunctions = await extensionMembers("pg_proc");
const extTypes = await extensionMembers("pg_type");

const out = [];
const say = (s = "") => out.push(s);
const section = (title, note) => {
  say("");
  say("-- " + "-".repeat(74));
  say(`-- ${title}`);
  if (note) for (const line of note.split("\n")) say(`-- ${line}`);
  say("-- " + "-".repeat(74));
  say("");
};

// -- header -------------------------------------------------------------------
const [{ version }] = await q("select version()");
say("-- Baseline schema for everything built before SA-4.1.");
say("--");
say("-- GENERATED by scripts/dump-schema.mjs from the live database. Objects created by the");
say("-- numbered migrations 0001+ are deliberately absent - this file runs first and they run");
say("-- after, so together they rebuild the whole schema from nothing.");
say("--");
say("-- Regenerate with:  node --env-file=.env.local scripts/dump-schema.mjs");
say("--");
say(`-- Source: ${version.split(" on ")[0]}`);
say("");
say("set check_function_bodies = off;");

// -- roles --------------------------------------------------------------------
// The single most important thing missing from this repository before now. `tenant_app` is what
// makes tenant isolation real: it is NOBYPASSRLS, so the row level security below actually applies
// to it, unlike service_role which bypasses everything. Nothing in the codebase created this role —
// it was made by hand in the Supabase dashboard, which meant a fresh database had no such role and
// the app's own connection string pointed at nothing.
//
// No password is emitted, deliberately. Set one out of band and put it in TENANT_DB_URL.
const appRoles = await q(`
  select rolname, rolcanlogin, rolbypassrls, rolinherit
  from pg_roles
  where rolname = 'tenant_app'`);

const schemaGrants = await q(`
  select coalesce(nullif(a.grantee::regrole::text, '-'), 'public') as grantee, a.privilege_type
  from pg_namespace n cross join lateral aclexplode(n.nspacl) a
  where n.nspname = 'public'
  order by grantee, a.privilege_type`);

if (appRoles.length) {
  section(
    "Roles",
    [
      "tenant_app is NOBYPASSRLS on purpose: it is the only reason the policies further down have",
      "any effect. service_role bypasses RLS entirely, so anything reached with the service key is",
      "unprotected by definition and must go through the admin plane instead.",
      "",
      "No password here. Set it out of band and put the result in TENANT_DB_URL.",
    ].join("\n"),
  );
  for (const r of appRoles) {
    const attrs = [
      r.rolcanlogin ? "login" : "nologin",
      r.rolbypassrls ? "bypassrls" : "nobypassrls",
      r.rolinherit ? "inherit" : "noinherit",
    ].join(" ");
    say("do $$ begin");
    say(`  create role ${r.rolname} with ${attrs};`);
    say("exception when duplicate_object then null; end $$;");
    // Re-assert on an existing role too, so a role created by hand with the wrong flags is fixed
    // rather than silently left permissive.
    say(`alter role ${r.rolname} with ${attrs};`);
  }
  say("");
  for (const g of schemaGrants) {
    if (g.grantee === "pg_database_owner" || g.grantee === "postgres") continue;
    say(`grant ${g.privilege_type.toLowerCase()} on schema public to ${g.grantee};`);
  }
}

// -- extensions ---------------------------------------------------------------
const exts = await q(`
  select extname, extnamespace::regnamespace::text as schema
  from pg_extension where extname not in ('plpgsql') order by extname`);
if (exts.length) {
  section("Extensions");
  for (const e of exts) say(`create extension if not exists "${e.extname}" with schema ${e.schema};`);
}

// -- enum types ---------------------------------------------------------------
const enums = (await q(`
  select t.oid, t.typname, array_agg(e.enumlabel::text order by e.enumsortorder) as labels
  from pg_type t
  join pg_enum e on e.enumtypid = t.oid
  join pg_namespace n on n.oid = t.typnamespace
  where n.nspname = 'public'
  group by t.oid, t.typname order by t.typname`))
  .filter((t) => !skip.types.has(t.typname.toLowerCase()) && !extTypes.has(Number(t.oid)));
if (enums.length) {
  section("Enum types");
  for (const t of enums) {
    // `create type` has no IF NOT EXISTS, so guard it - this file must be safe to re-run.
    say("do $$ begin");
    say(`  create type public.${t.typname} as enum (${t.labels.map((l) => `'${l.replace(/'/g, "''")}'`).join(", ")});`);
    say("exception when duplicate_object then null; end $$;");
  }
}

// -- tables -------------------------------------------------------------------
const tables = (await q(`
  select c.oid, c.relname, c.relrowsecurity, c.relforcerowsecurity
  from pg_class c join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public' and c.relkind = 'r'
  order by c.relname`)).filter((t) => !skip.tables.has(t.relname.toLowerCase()));

const fkeys = [];
if (tables.length) {
  section(
    "Tables",
    "Foreign keys are added at the end, after every table exists, so this file has no\nordering requirement between tables.",
  );
  for (const t of tables) {
    const cols = await q(
      `select a.attname, format_type(a.atttypid, a.atttypmod) as type, a.attnotnull,
              pg_get_expr(d.adbin, d.adrelid) as default_expr, a.attidentity, a.attgenerated
       from pg_attribute a
       left join pg_attrdef d on d.adrelid = a.attrelid and d.adnum = a.attnum
       where a.attrelid = $1 and a.attnum > 0 and not a.attisdropped
       order by a.attnum`,
      [t.oid],
    );

    const cons = await q(
      `select conname, contype, pg_get_constraintdef(oid) as def
       from pg_constraint where conrelid = $1 order by contype, conname`,
      [t.oid],
    );

    const lines = cols.map((c) => {
      let s = `  ${c.attname} ${c.type}`;
      if (c.attgenerated === "s") s += ` generated always as (${c.default_expr}) stored`;
      else if (c.attidentity) s += ` generated ${c.attidentity === "a" ? "always" : "by default"} as identity`;
      else if (c.default_expr) s += ` default ${c.default_expr}`;
      if (c.attnotnull) s += " not null";
      return s;
    });

    // Inline everything except foreign keys.
    for (const c of cons.filter((c) => c.contype !== "f")) {
      lines.push(`  constraint ${c.conname} ${c.def}`);
    }
    for (const c of cons.filter((c) => c.contype === "f")) {
      fkeys.push({ table: t.relname, name: c.conname, def: c.def });
    }

    say(`create table if not exists public.${t.relname} (`);
    say(lines.join(",\n"));
    say(");");
    say("");
  }
}

// -- indexes ------------------------------------------------------------------
const idx = (await q(`
  select ci.relname as name, pg_get_indexdef(i.indexrelid) as def, ct.relname as table_name
  from pg_index i
  join pg_class ci on ci.oid = i.indexrelid
  join pg_class ct on ct.oid = i.indrelid
  join pg_namespace n on n.oid = ct.relnamespace
  where n.nspname = 'public'
    and not exists (select 1 from pg_constraint c where c.conindid = i.indexrelid)
  order by ct.relname, ci.relname`))
  .filter((r) => !skip.indexes.has(r.name.toLowerCase()) && !skip.tables.has(r.table_name.toLowerCase()));
if (idx.length) {
  section("Indexes");
  // pg_get_indexdef emits `CREATE INDEX name` - make it re-runnable.
  for (const r of idx) say(r.def.replace(/^create (unique )?index /i, (m) => `${m}if not exists `) + ";");
}

// -- views --------------------------------------------------------------------
const views = await q(`
  select c.relname, c.relkind, pg_get_viewdef(c.oid, true) as def
  from pg_class c join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public' and c.relkind in ('v','m') order by c.relname`);
if (views.length) {
  section("Views");
  for (const v of views) {
    say(
      v.relkind === "m"
        ? `create materialized view if not exists public.${v.relname} as\n${v.def}`
        : `create or replace view public.${v.relname} as\n${v.def}`,
    );
    say("");
  }
}

// -- functions ----------------------------------------------------------------
const funcs = (await q(`
  select p.oid, p.proname
  from pg_proc p join pg_namespace n on n.oid = p.pronamespace
  where n.nspname = 'public' and p.prokind in ('f','p')
  order by p.proname`))
  .filter((f) => !skip.functions.has(f.proname.toLowerCase()) && !extFunctions.has(Number(f.oid)));
if (funcs.length) {
  section("Functions");
  for (const f of funcs) {
    try {
      const [{ def }] = await q("select pg_get_functiondef($1) as def", [f.oid]);
      say(def.trimEnd().endsWith(";") ? def.trimEnd() : def.trimEnd() + ";");
      say("");
    } catch (e) {
      say(`-- could not read public.${f.proname}: ${e.message}`);
    }
  }
}

// -- triggers -----------------------------------------------------------------
const trigs = (await q(`
  select t.tgname, ct.relname as table_name, pg_get_triggerdef(t.oid) as def
  from pg_trigger t
  join pg_class ct on ct.oid = t.tgrelid
  join pg_namespace n on n.oid = ct.relnamespace
  where n.nspname = 'public' and not t.tgisinternal
  order by ct.relname, t.tgname`))
  .filter((t) => !skip.triggers.has(t.tgname.toLowerCase()) && !skip.tables.has(t.table_name.toLowerCase()));
if (trigs.length) {
  section("Triggers");
  for (const t of trigs) {
    // Triggers have no IF NOT EXISTS, so drop first rather than fail on a re-run.
    say(`drop trigger if exists ${t.tgname} on public.${t.table_name};`);
    say(t.def + ";");
  }
}

// -- foreign keys -------------------------------------------------------------
if (fkeys.length) {
  section("Foreign keys");
  for (const fk of fkeys) {
    say("do $$ begin");
    say(`  alter table public.${fk.table} add constraint ${fk.name} ${fk.def};`);
    say("exception when duplicate_object then null; end $$;");
  }
}

// -- row level security -------------------------------------------------------
const rlsTables = tables.filter((t) => t.relrowsecurity);
const policies = (await q(`
  select tablename, policyname, permissive, roles::text[] as roles, cmd, qual, with_check
  from pg_policies where schemaname = 'public'
  order by tablename, policyname`)).filter((p) => !skip.tables.has(p.tablename.toLowerCase()));

if (rlsTables.length || policies.length) {
  section(
    "Row level security",
    "This is the load-bearing half. Tenant isolation is not enforced in application code - it is\n" +
      "the tenant_app role being NOBYPASSRLS plus these policies. A restore that recreated the\n" +
      "tables and skipped this section would look correct and be wide open.",
  );
  for (const t of rlsTables) {
    say(`alter table public.${t.relname} enable row level security;`);
    if (t.relforcerowsecurity) say(`alter table public.${t.relname} force row level security;`);
  }
  say("");
  for (const p of policies) {
    say(`drop policy if exists ${p.policyname} on public.${p.tablename};`);
    let s = `create policy ${p.policyname} on public.${p.tablename}`;
    if (p.permissive === "RESTRICTIVE") s += " as restrictive";
    s += ` for ${p.cmd.toLowerCase()}`;
    const roles = (p.roles || []).filter((r) => r !== "-");
    if (roles.length) s += ` to ${roles.join(", ")}`;
    if (p.qual) s += `\n  using (${p.qual})`;
    if (p.with_check) s += `\n  with check (${p.with_check})`;
    say(s + ";");
  }
}

// -- grants -------------------------------------------------------------------
const grants = (await q(`
  select c.relname, c.relkind,
         coalesce(nullif(a.grantee::regrole::text, '-'), 'public') as grantee,
         a.privilege_type
  from pg_class c
  join pg_namespace n on n.oid = c.relnamespace
  cross join lateral aclexplode(c.relacl) a
  where n.nspname = 'public' and c.relkind in ('r','v','m','S')
  order by c.relname, grantee, a.privilege_type`))
  .filter((g) => !skip.tables.has(g.relname.toLowerCase()));

if (grants.length) {
  section(
    "Grants",
    "Emitted as an explicit REVOKE ALL followed by exactly the grants the live database has.\n" +
      "The revoke is the point: several tables are append-only (the audit log above all) and that\n" +
      "property is a missing UPDATE grant, not a trigger. Restoring grants additively would\n" +
      "silently hand back the DELETE that was taken away.",
  );

  const byTable = new Map();
  for (const g of grants) {
    if (!byTable.has(g.relname)) byTable.set(g.relname, new Map());
    const t = byTable.get(g.relname);
    if (!t.has(g.grantee)) t.set(g.grantee, []);
    t.get(g.grantee).push(g.privilege_type.toLowerCase());
  }
  for (const [table, byGrantee] of byTable) {
    // Revoke from every role this file can grant to, not just the public ones. The revoke is the
    // point: append-only tables are append-only because UPDATE and DELETE are absent, and an
    // additive restore would hand them back without anyone noticing.
    say(`revoke all on public.${table} from anon, authenticated, service_role, tenant_app, public;`);
    for (const [grantee, privs] of byGrantee) {
      // The owner's implicit full grant is noise; every other row is a real decision.
      if (grantee === "postgres" && privs.length >= 7) continue;
      say(`grant ${[...new Set(privs)].sort().join(", ")} on public.${table} to ${grantee};`);
    }
    say("");
  }
}

say("-- end of baseline");
say("");

await client.end();

const text = out.join("\n");
if (toStdout) {
  process.stdout.write(text);
} else {
  writeFileSync(OUT, text, "utf8");
  console.log(`wrote ${OUT}`);
  console.log(
    [
      `${tables.length} tables`,
      `${enums.length} enums`,
      `${idx.length} indexes`,
      `${views.length} views`,
      `${funcs.length} functions`,
      `${trigs.length} triggers`,
      `${fkeys.length} foreign keys`,
      `${policies.length} policies`,
    ].join(" | "),
  );
  console.log(`${text.split("\n").length} lines`);
}
