-- Platform reference data.
--
-- GENERATED by scripts/dump-reference-data.mjs. These four catalogs are a contract with the
-- source tree rather than customer data: check-feature-keys.mjs asserts that every feature key
-- named in TypeScript has a row here, so an empty table is a failing build, not an empty screen.
--
-- Upserts rather than inserts, so re-running never fights an existing database. Timestamps and
-- anything server-generated are left out and left to their defaults.

-- feature_modules (9 rows)
insert into public.feature_modules (key, label, sort_order) values
  ('book', 'Book of business', 1),
  ('acquisition', 'Acquisition', 2),
  ('sell', 'Sell', 3),
  ('retention', 'Retention', 4),
  ('insight', 'Insight', 5),
  ('partners', 'Partners', 6),
  ('accounting', 'Accounting', 7),
  ('compliance', 'Compliance', 8),
  ('agency', 'Agency & teams', 9)
on conflict (key) do update set
  label = excluded.label,
  sort_order = excluded.sort_order
;

-- features (27 rows)
insert into public.features (id, feature_key, label, module, description, sort_order, is_archived) values
  ('0f447a7c-e80d-41f2-b1d9-37850a29588a', 'book_of_business', 'Policies & book of business', 'book', null, 1, false),
  ('c748332e-7767-4fc0-b0d2-d285b3591f91', 'statement_ingestion', 'Carrier statement import', 'book', null, 2, false),
  ('20c63370-b0ef-4d94-8608-d22978fd2458', 'commission_ledger', 'Commission ledger', 'book', null, 3, false),
  ('555916fd-1ef6-482b-8b1a-ff53f36c3838', 'appointment_vault', 'Appointments & contract levels', 'book', null, 4, false),
  ('09ea4148-e2de-4192-949e-a2c81a7a51ed', 'discrepancy_report', 'Discrepancy report', 'book', null, 5, false),
  ('a7315e5f-c67e-4d3b-8af0-59d3fa407ca7', 'inbound_transfers', 'Inbound live transfers', 'acquisition', null, 1, false),
  ('689a8c98-a126-4ee7-8af3-cbd3b9ec082c', 'outbound_dialing', 'Outbound dialer', 'acquisition', null, 2, false),
  ('26430ad4-8aa6-4dc6-9b01-a7151c632d24', 'lead_import', 'Purchased list import', 'acquisition', null, 3, false),
  ('ee470be3-60f1-4823-b40b-f8d9959800f5', 'duplicate_detection', 'Duplicate & existing-customer check', 'acquisition', null, 4, false),
  ('42a1c81a-d471-4dcd-9d2d-47d45071b548', 'quoting', 'Quoting', 'sell', null, 1, false),
  ('f95a26be-064c-44e8-8b24-51bd3b640a4f', 'applications', 'Dynamic application forms', 'sell', null, 2, false),
  ('e6c1ac97-ac86-4f46-9be1-b76aecafc9dd', 'draft_date_optimizer', 'Draft-date optimiser', 'sell', null, 3, false),
  ('bfa536bb-f9cb-4767-b017-389bc49e1325', 'callback_calendar', 'Callback calendar', 'sell', null, 4, false),
  ('2242a70c-e2f0-49e9-8746-474ecb4a47f5', 'daily_deal_flow', 'Daily deal flow', 'sell', null, 5, false),
  ('411c933d-cfa0-4e25-bbdd-146e0a473a27', 'chargeback_radar', 'Predictive lapse scoring', 'retention', null, 1, false),
  ('666e8df4-74d1-4e2b-bf4a-8bff1e50403a', 'payment_repair', 'Failed-payment repair', 'retention', null, 2, false),
  ('d72d8ad6-1aec-46bf-a247-2614b3d7205b', 'winback', 'Win-back campaigns', 'retention', null, 3, false),
  ('ebd9a36f-784a-4075-8c22-8f3dcc5359a4', 'true_cpa', 'True cost per acquisition', 'insight', null, 1, false),
  ('59b44bf3-36b6-4fe9-93ea-688663f5f2d5', 'cohort_persistency', 'Persistency by lead source', 'insight', null, 2, false),
  ('5968c6a6-f218-406b-b746-0ce347b51179', 'publisher_records', 'Publisher management', 'partners', null, 1, false),
  ('9adde673-8e28-49ff-ad72-708ecf1a866e', 'payout_runs', 'Payout runs', 'partners', null, 2, false),
  ('d0505330-13b9-4a4d-b5c5-84dc697fcf62', 'partner_portal', 'External publisher logins', 'partners', null, 3, false),
  ('c16e69ad-d6d3-41fd-887e-4f1ff45b490c', 'profit_and_loss', 'Full P&L', 'accounting', null, 1, false),
  ('0f449f60-2e95-4a05-9222-8131baf246e6', 'tax_summaries', 'Tax summaries & 1099', 'accounting', null, 2, false),
  ('390ab027-3f94-41d9-84ac-fa2ef7b92806', 'tcpa_checker', 'TCPA / DNC checker', 'compliance', null, 1, false),
  ('719f2ce9-4b40-4b52-a8ba-7e9f66548cc7', 'consent_locker', 'Consent certificate storage', 'compliance', null, 2, false),
  ('89d09b54-3ff0-4afb-994b-1e9e0441b459', 'litigation_packet', 'Litigation packet export', 'compliance', null, 3, false)
on conflict (key) do update set
  id = excluded.id,
  feature_key = excluded.feature_key,
  label = excluded.label,
  module = excluded.module,
  description = excluded.description,
  sort_order = excluded.sort_order,
  is_archived = excluded.is_archived
;

-- meters (6 rows)
insert into public.meters (meter_key, unit, label, default_hard_cap, sort_order) values
  ('tcpa_checks', 'check', 'TCPA checks', true, 1),
  ('dnc_lookups', 'lookup', 'DNC lookups', true, 2),
  ('dialer_minutes', 'minute', 'Dialer minutes', true, 3),
  ('sms_segments', 'segment', 'SMS segments', true, 4),
  ('statement_pages', 'page', 'Statement pages', false, 5),
  ('esign_envelopes', 'envelope', 'E-sign envelopes', true, 6)
on conflict (key) do update set
  meter_key = excluded.meter_key,
  unit = excluded.unit,
  label = excluded.label,
  default_hard_cap = excluded.default_hard_cap,
  sort_order = excluded.sort_order
;

-- payment_providers: no rows