import React from "react";
import { useCurrentFrame } from "remotion";
import { AdminBrowser, Backdrop, Badge, Callout, Kicker, Label, Panel, Progress, Tiny, c, appear, bounce } from "./shared";

export const SuperAdminCatalog: React.FC = () => {
  const frame = useCurrentFrame();
  return <Backdrop><Progress step={5} total={9} /><div style={{ position: "absolute", left: 66, top: 66, ...appear(frame, 5) }}><Kicker>05 · Catalog and entitlements</Kicker><div style={{ marginTop: 10, fontSize: 33, fontWeight: 800 }}>Define what each plan unlocks.</div></div><div style={{ position: "absolute", left: 105, top: 164, ...appear(frame, 14) }}><AdminBrowser active="Plans"><div style={{ display: "flex", justifyContent: "space-between", alignItems: "start" }}><div><div style={{ color: c.navy, fontSize: 23, fontWeight: 800 }}>Product catalog</div><Tiny>Plans, versions, add-ons, feature flags, and the access model.</Tiny></div><div style={{ display: "flex", gap: 7 }}><Badge>Plans</Badge><Badge tone="purple">Features</Badge><Badge tone="orange">Add-ons</Badge></div></div><div style={{ display: "grid", gridTemplateColumns: "repeat(3,1fr)", gap: 12, marginTop: 23 }}><CatalogCard title="Plans" color={c.blue} value="3 active" lines={["Basic · $249/mo", "Advanced · $449/mo", "Archive old plans safely"]} /><CatalogCard title="Features" color={c.purple} value="18 cataloged" lines={["Lead workspace", "Dialer & automations", "Kill switches"]} /><CatalogCard title="Add-ons" color={c.orange} value="6 available" lines={["Optional paid modules", "Plan-compatible pricing", "Entitlement sync"]} /></div><Panel style={{ marginTop: 15 }}><div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}><div><Label>Plan version editor</Label><Tiny>Pricing and feature selection save together as a new version.</Tiny></div><Badge tone="green">Entitlements synchronized</Badge></div><div style={{ display: "flex", gap: 8, marginTop: 18 }}>{["Pricing", "Feature access", "Seat limits", "Trial days", "Archive / restore"].map((item, i) => <div key={item} style={{ flex: 1, padding: "11px 8px", borderRadius: 7, background: i === 1 ? "#f1edff" : "#f5f9fc", color: i === 1 ? c.purple : c.ink, fontSize: 10, textAlign: "center", fontWeight: 800 }}>{item}</div>)}</div></Panel></AdminBrowser><Callout title="Product truth" body="A plan is not only a price—it is the exact set of capabilities the tenant can use." top={203} right={-246} /><div style={{ position: "absolute", top: 424, right: -245, ...bounce(frame, 104), color: "#b5f5d6", fontSize: 17, fontWeight: 800 }}>✓ Access follows the plan</div></div><div style={{ position: "absolute", right: 66, bottom: 25, color: "rgba(255,255,255,.58)", fontSize: 10, letterSpacing: 1.2 }}>CATALOG · PRICING · FEATURES · ENTITLEMENTS</div></Backdrop>;
};

const CatalogCard: React.FC<{ title: string; color: string; value: string; lines: string[] }> = ({ title, color, value, lines }) => <Panel style={{ minHeight: 183 }}><div style={{ width: 34, height: 34, borderRadius: 10, background: `${color}18`, color, display: "grid", placeItems: "center", fontWeight: 900, fontSize: 17 }}>◆</div><div style={{ marginTop: 12, color: c.navy, fontSize: 18, fontWeight: 800 }}>{title}</div><div style={{ marginTop: 4, color, fontSize: 11, fontWeight: 800 }}>{value}</div><div style={{ display: "grid", gap: 8, marginTop: 14 }}>{lines.map((line) => <div key={line} style={{ color: c.muted, fontSize: 10 }}>✓ {line}</div>)}</div></Panel>;
